// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.su.msg;

public final class LoginMsg {
  private LoginMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Login)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 1;</code>
     */
    boolean hasAccount();
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 1;</code>
     */
    java.lang.String getAccount();
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * Protobuf type {@code Login}
   */
  public  static final class Login extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Login)
      LoginOrBuilder {
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login() {
      account_ = "";
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              account_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.LoginMsg.internal_static_Login_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.LoginMsg.internal_static_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.LoginMsg.Login.class, com.su.msg.LoginMsg.Login.Builder.class);
    }

    private int bitField0_;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private volatile java.lang.Object account_;
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 1;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 1;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, account_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, account_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.LoginMsg.Login)) {
        return super.equals(obj);
      }
      com.su.msg.LoginMsg.Login other = (com.su.msg.LoginMsg.Login) obj;

      boolean result = true;
      result = result && (hasAccount() == other.hasAccount());
      if (hasAccount()) {
        result = result && getAccount()
            .equals(other.getAccount());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAccount()) {
        hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAccount().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.LoginMsg.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.LoginMsg.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.LoginMsg.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.LoginMsg.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.LoginMsg.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.LoginMsg.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.LoginMsg.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.LoginMsg.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.LoginMsg.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.LoginMsg.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.LoginMsg.Login prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * Protobuf type {@code Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Login)
        com.su.msg.LoginMsg.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.LoginMsg.internal_static_Login_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.LoginMsg.internal_static_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.LoginMsg.Login.class, com.su.msg.LoginMsg.Login.Builder.class);
      }

      // Construct using com.su.msg.LoginMsg.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.LoginMsg.internal_static_Login_descriptor;
      }

      public com.su.msg.LoginMsg.Login getDefaultInstanceForType() {
        return com.su.msg.LoginMsg.Login.getDefaultInstance();
      }

      public com.su.msg.LoginMsg.Login build() {
        com.su.msg.LoginMsg.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.LoginMsg.Login buildPartial() {
        com.su.msg.LoginMsg.Login result = new com.su.msg.LoginMsg.Login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.LoginMsg.Login) {
          return mergeFrom((com.su.msg.LoginMsg.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.LoginMsg.Login other) {
        if (other == com.su.msg.LoginMsg.Login.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          bitField0_ |= 0x00000001;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.LoginMsg.Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.LoginMsg.Login) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object account_ = "";
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 1;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 1;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            account_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 1;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 1;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 1;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Login)
    }

    // @@protoc_insertion_point(class_scope:Login)
    private static final com.su.msg.LoginMsg.Login DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.LoginMsg.Login();
    }

    public static com.su.msg.LoginMsg.Login getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Login>
        PARSER = new com.google.protobuf.AbstractParser<Login>() {
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Login(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    public com.su.msg.LoginMsg.Login getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Login_OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Login_)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 玩家数据
     * </pre>
     *
     * <code>optional ._Player player = 1;</code>
     */
    boolean hasPlayer();
    /**
     * <pre>
     * 玩家数据
     * </pre>
     *
     * <code>optional ._Player player = 1;</code>
     */
    com.su.msg.PlayerMsg._Player getPlayer();
    /**
     * <pre>
     * 玩家数据
     * </pre>
     *
     * <code>optional ._Player player = 1;</code>
     */
    com.su.msg.PlayerMsg._PlayerOrBuilder getPlayerOrBuilder();

    /**
     * <pre>
     * 背包数据
     * </pre>
     *
     * <code>repeated ._Grid grid = 2;</code>
     */
    java.util.List<com.su.msg.BagMsg._Grid> 
        getGridList();
    /**
     * <pre>
     * 背包数据
     * </pre>
     *
     * <code>repeated ._Grid grid = 2;</code>
     */
    com.su.msg.BagMsg._Grid getGrid(int index);
    /**
     * <pre>
     * 背包数据
     * </pre>
     *
     * <code>repeated ._Grid grid = 2;</code>
     */
    int getGridCount();
    /**
     * <pre>
     * 背包数据
     * </pre>
     *
     * <code>repeated ._Grid grid = 2;</code>
     */
    java.util.List<? extends com.su.msg.BagMsg._GridOrBuilder> 
        getGridOrBuilderList();
    /**
     * <pre>
     * 背包数据
     * </pre>
     *
     * <code>repeated ._Grid grid = 2;</code>
     */
    com.su.msg.BagMsg._GridOrBuilder getGridOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Login_}
   */
  public  static final class Login_ extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Login_)
      Login_OrBuilder {
    // Use Login_.newBuilder() to construct.
    private Login_(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Login_() {
      grid_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Login_(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.su.msg.PlayerMsg._Player.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = player_.toBuilder();
              }
              player_ = input.readMessage(com.su.msg.PlayerMsg._Player.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(player_);
                player_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                grid_ = new java.util.ArrayList<com.su.msg.BagMsg._Grid>();
                mutable_bitField0_ |= 0x00000002;
              }
              grid_.add(
                  input.readMessage(com.su.msg.BagMsg._Grid.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          grid_ = java.util.Collections.unmodifiableList(grid_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.LoginMsg.internal_static_Login__descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.LoginMsg.internal_static_Login__fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.LoginMsg.Login_.class, com.su.msg.LoginMsg.Login_.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYER_FIELD_NUMBER = 1;
    private com.su.msg.PlayerMsg._Player player_;
    /**
     * <pre>
     * 玩家数据
     * </pre>
     *
     * <code>optional ._Player player = 1;</code>
     */
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 玩家数据
     * </pre>
     *
     * <code>optional ._Player player = 1;</code>
     */
    public com.su.msg.PlayerMsg._Player getPlayer() {
      return player_ == null ? com.su.msg.PlayerMsg._Player.getDefaultInstance() : player_;
    }
    /**
     * <pre>
     * 玩家数据
     * </pre>
     *
     * <code>optional ._Player player = 1;</code>
     */
    public com.su.msg.PlayerMsg._PlayerOrBuilder getPlayerOrBuilder() {
      return player_ == null ? com.su.msg.PlayerMsg._Player.getDefaultInstance() : player_;
    }

    public static final int GRID_FIELD_NUMBER = 2;
    private java.util.List<com.su.msg.BagMsg._Grid> grid_;
    /**
     * <pre>
     * 背包数据
     * </pre>
     *
     * <code>repeated ._Grid grid = 2;</code>
     */
    public java.util.List<com.su.msg.BagMsg._Grid> getGridList() {
      return grid_;
    }
    /**
     * <pre>
     * 背包数据
     * </pre>
     *
     * <code>repeated ._Grid grid = 2;</code>
     */
    public java.util.List<? extends com.su.msg.BagMsg._GridOrBuilder> 
        getGridOrBuilderList() {
      return grid_;
    }
    /**
     * <pre>
     * 背包数据
     * </pre>
     *
     * <code>repeated ._Grid grid = 2;</code>
     */
    public int getGridCount() {
      return grid_.size();
    }
    /**
     * <pre>
     * 背包数据
     * </pre>
     *
     * <code>repeated ._Grid grid = 2;</code>
     */
    public com.su.msg.BagMsg._Grid getGrid(int index) {
      return grid_.get(index);
    }
    /**
     * <pre>
     * 背包数据
     * </pre>
     *
     * <code>repeated ._Grid grid = 2;</code>
     */
    public com.su.msg.BagMsg._GridOrBuilder getGridOrBuilder(
        int index) {
      return grid_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getPlayer());
      }
      for (int i = 0; i < grid_.size(); i++) {
        output.writeMessage(2, grid_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlayer());
      }
      for (int i = 0; i < grid_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, grid_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.LoginMsg.Login_)) {
        return super.equals(obj);
      }
      com.su.msg.LoginMsg.Login_ other = (com.su.msg.LoginMsg.Login_) obj;

      boolean result = true;
      result = result && (hasPlayer() == other.hasPlayer());
      if (hasPlayer()) {
        result = result && getPlayer()
            .equals(other.getPlayer());
      }
      result = result && getGridList()
          .equals(other.getGridList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlayer()) {
        hash = (37 * hash) + PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getPlayer().hashCode();
      }
      if (getGridCount() > 0) {
        hash = (37 * hash) + GRID_FIELD_NUMBER;
        hash = (53 * hash) + getGridList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.LoginMsg.Login_ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.LoginMsg.Login_ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.LoginMsg.Login_ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.LoginMsg.Login_ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.LoginMsg.Login_ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.LoginMsg.Login_ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.LoginMsg.Login_ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.LoginMsg.Login_ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.LoginMsg.Login_ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.LoginMsg.Login_ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.LoginMsg.Login_ prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Login_}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Login_)
        com.su.msg.LoginMsg.Login_OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.LoginMsg.internal_static_Login__descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.LoginMsg.internal_static_Login__fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.LoginMsg.Login_.class, com.su.msg.LoginMsg.Login_.Builder.class);
      }

      // Construct using com.su.msg.LoginMsg.Login_.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlayerFieldBuilder();
          getGridFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (playerBuilder_ == null) {
          player_ = null;
        } else {
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (gridBuilder_ == null) {
          grid_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          gridBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.LoginMsg.internal_static_Login__descriptor;
      }

      public com.su.msg.LoginMsg.Login_ getDefaultInstanceForType() {
        return com.su.msg.LoginMsg.Login_.getDefaultInstance();
      }

      public com.su.msg.LoginMsg.Login_ build() {
        com.su.msg.LoginMsg.Login_ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.LoginMsg.Login_ buildPartial() {
        com.su.msg.LoginMsg.Login_ result = new com.su.msg.LoginMsg.Login_(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (playerBuilder_ == null) {
          result.player_ = player_;
        } else {
          result.player_ = playerBuilder_.build();
        }
        if (gridBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            grid_ = java.util.Collections.unmodifiableList(grid_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.grid_ = grid_;
        } else {
          result.grid_ = gridBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.LoginMsg.Login_) {
          return mergeFrom((com.su.msg.LoginMsg.Login_)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.LoginMsg.Login_ other) {
        if (other == com.su.msg.LoginMsg.Login_.getDefaultInstance()) return this;
        if (other.hasPlayer()) {
          mergePlayer(other.getPlayer());
        }
        if (gridBuilder_ == null) {
          if (!other.grid_.isEmpty()) {
            if (grid_.isEmpty()) {
              grid_ = other.grid_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureGridIsMutable();
              grid_.addAll(other.grid_);
            }
            onChanged();
          }
        } else {
          if (!other.grid_.isEmpty()) {
            if (gridBuilder_.isEmpty()) {
              gridBuilder_.dispose();
              gridBuilder_ = null;
              grid_ = other.grid_;
              bitField0_ = (bitField0_ & ~0x00000002);
              gridBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGridFieldBuilder() : null;
            } else {
              gridBuilder_.addAllMessages(other.grid_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.LoginMsg.Login_ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.LoginMsg.Login_) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.su.msg.PlayerMsg._Player player_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.su.msg.PlayerMsg._Player, com.su.msg.PlayerMsg._Player.Builder, com.su.msg.PlayerMsg._PlayerOrBuilder> playerBuilder_;
      /**
       * <pre>
       * 玩家数据
       * </pre>
       *
       * <code>optional ._Player player = 1;</code>
       */
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 玩家数据
       * </pre>
       *
       * <code>optional ._Player player = 1;</code>
       */
      public com.su.msg.PlayerMsg._Player getPlayer() {
        if (playerBuilder_ == null) {
          return player_ == null ? com.su.msg.PlayerMsg._Player.getDefaultInstance() : player_;
        } else {
          return playerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 玩家数据
       * </pre>
       *
       * <code>optional ._Player player = 1;</code>
       */
      public Builder setPlayer(com.su.msg.PlayerMsg._Player value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          player_ = value;
          onChanged();
        } else {
          playerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * 玩家数据
       * </pre>
       *
       * <code>optional ._Player player = 1;</code>
       */
      public Builder setPlayer(
          com.su.msg.PlayerMsg._Player.Builder builderForValue) {
        if (playerBuilder_ == null) {
          player_ = builderForValue.build();
          onChanged();
        } else {
          playerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * 玩家数据
       * </pre>
       *
       * <code>optional ._Player player = 1;</code>
       */
      public Builder mergePlayer(com.su.msg.PlayerMsg._Player value) {
        if (playerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              player_ != null &&
              player_ != com.su.msg.PlayerMsg._Player.getDefaultInstance()) {
            player_ =
              com.su.msg.PlayerMsg._Player.newBuilder(player_).mergeFrom(value).buildPartial();
          } else {
            player_ = value;
          }
          onChanged();
        } else {
          playerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * 玩家数据
       * </pre>
       *
       * <code>optional ._Player player = 1;</code>
       */
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          player_ = null;
          onChanged();
        } else {
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       * 玩家数据
       * </pre>
       *
       * <code>optional ._Player player = 1;</code>
       */
      public com.su.msg.PlayerMsg._Player.Builder getPlayerBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPlayerFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 玩家数据
       * </pre>
       *
       * <code>optional ._Player player = 1;</code>
       */
      public com.su.msg.PlayerMsg._PlayerOrBuilder getPlayerOrBuilder() {
        if (playerBuilder_ != null) {
          return playerBuilder_.getMessageOrBuilder();
        } else {
          return player_ == null ?
              com.su.msg.PlayerMsg._Player.getDefaultInstance() : player_;
        }
      }
      /**
       * <pre>
       * 玩家数据
       * </pre>
       *
       * <code>optional ._Player player = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.su.msg.PlayerMsg._Player, com.su.msg.PlayerMsg._Player.Builder, com.su.msg.PlayerMsg._PlayerOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.su.msg.PlayerMsg._Player, com.su.msg.PlayerMsg._Player.Builder, com.su.msg.PlayerMsg._PlayerOrBuilder>(
                  getPlayer(),
                  getParentForChildren(),
                  isClean());
          player_ = null;
        }
        return playerBuilder_;
      }

      private java.util.List<com.su.msg.BagMsg._Grid> grid_ =
        java.util.Collections.emptyList();
      private void ensureGridIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          grid_ = new java.util.ArrayList<com.su.msg.BagMsg._Grid>(grid_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.su.msg.BagMsg._Grid, com.su.msg.BagMsg._Grid.Builder, com.su.msg.BagMsg._GridOrBuilder> gridBuilder_;

      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public java.util.List<com.su.msg.BagMsg._Grid> getGridList() {
        if (gridBuilder_ == null) {
          return java.util.Collections.unmodifiableList(grid_);
        } else {
          return gridBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public int getGridCount() {
        if (gridBuilder_ == null) {
          return grid_.size();
        } else {
          return gridBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public com.su.msg.BagMsg._Grid getGrid(int index) {
        if (gridBuilder_ == null) {
          return grid_.get(index);
        } else {
          return gridBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public Builder setGrid(
          int index, com.su.msg.BagMsg._Grid value) {
        if (gridBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGridIsMutable();
          grid_.set(index, value);
          onChanged();
        } else {
          gridBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public Builder setGrid(
          int index, com.su.msg.BagMsg._Grid.Builder builderForValue) {
        if (gridBuilder_ == null) {
          ensureGridIsMutable();
          grid_.set(index, builderForValue.build());
          onChanged();
        } else {
          gridBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public Builder addGrid(com.su.msg.BagMsg._Grid value) {
        if (gridBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGridIsMutable();
          grid_.add(value);
          onChanged();
        } else {
          gridBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public Builder addGrid(
          int index, com.su.msg.BagMsg._Grid value) {
        if (gridBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGridIsMutable();
          grid_.add(index, value);
          onChanged();
        } else {
          gridBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public Builder addGrid(
          com.su.msg.BagMsg._Grid.Builder builderForValue) {
        if (gridBuilder_ == null) {
          ensureGridIsMutable();
          grid_.add(builderForValue.build());
          onChanged();
        } else {
          gridBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public Builder addGrid(
          int index, com.su.msg.BagMsg._Grid.Builder builderForValue) {
        if (gridBuilder_ == null) {
          ensureGridIsMutable();
          grid_.add(index, builderForValue.build());
          onChanged();
        } else {
          gridBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public Builder addAllGrid(
          java.lang.Iterable<? extends com.su.msg.BagMsg._Grid> values) {
        if (gridBuilder_ == null) {
          ensureGridIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, grid_);
          onChanged();
        } else {
          gridBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public Builder clearGrid() {
        if (gridBuilder_ == null) {
          grid_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          gridBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public Builder removeGrid(int index) {
        if (gridBuilder_ == null) {
          ensureGridIsMutable();
          grid_.remove(index);
          onChanged();
        } else {
          gridBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public com.su.msg.BagMsg._Grid.Builder getGridBuilder(
          int index) {
        return getGridFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public com.su.msg.BagMsg._GridOrBuilder getGridOrBuilder(
          int index) {
        if (gridBuilder_ == null) {
          return grid_.get(index);  } else {
          return gridBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public java.util.List<? extends com.su.msg.BagMsg._GridOrBuilder> 
           getGridOrBuilderList() {
        if (gridBuilder_ != null) {
          return gridBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(grid_);
        }
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public com.su.msg.BagMsg._Grid.Builder addGridBuilder() {
        return getGridFieldBuilder().addBuilder(
            com.su.msg.BagMsg._Grid.getDefaultInstance());
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public com.su.msg.BagMsg._Grid.Builder addGridBuilder(
          int index) {
        return getGridFieldBuilder().addBuilder(
            index, com.su.msg.BagMsg._Grid.getDefaultInstance());
      }
      /**
       * <pre>
       * 背包数据
       * </pre>
       *
       * <code>repeated ._Grid grid = 2;</code>
       */
      public java.util.List<com.su.msg.BagMsg._Grid.Builder> 
           getGridBuilderList() {
        return getGridFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.su.msg.BagMsg._Grid, com.su.msg.BagMsg._Grid.Builder, com.su.msg.BagMsg._GridOrBuilder> 
          getGridFieldBuilder() {
        if (gridBuilder_ == null) {
          gridBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.su.msg.BagMsg._Grid, com.su.msg.BagMsg._Grid.Builder, com.su.msg.BagMsg._GridOrBuilder>(
                  grid_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          grid_ = null;
        }
        return gridBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Login_)
    }

    // @@protoc_insertion_point(class_scope:Login_)
    private static final com.su.msg.LoginMsg.Login_ DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.LoginMsg.Login_();
    }

    public static com.su.msg.LoginMsg.Login_ getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Login_>
        PARSER = new com.google.protobuf.AbstractParser<Login_>() {
      public Login_ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Login_(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Login_> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Login_> getParserForType() {
      return PARSER;
    }

    public com.su.msg.LoginMsg.Login_ getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login__descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login__fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Login.proto\032\014Player.proto\032\tBag.proto\"&" +
      "\n\005Login\022\017\n\007account\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"8" +
      "\n\006Login_\022\030\n\006player\030\001 \001(\0132\010._Player\022\024\n\004gr" +
      "id\030\002 \003(\0132\006._GridB\030\n\ncom.su.msgB\010LoginMsg" +
      "H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.su.msg.PlayerMsg.getDescriptor(),
          com.su.msg.BagMsg.getDescriptor(),
        }, assigner);
    internal_static_Login_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login_descriptor,
        new java.lang.String[] { "Account", "Name", });
    internal_static_Login__descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Login__fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login__descriptor,
        new java.lang.String[] { "Player", "Grid", });
    com.su.msg.PlayerMsg.getDescriptor();
    com.su.msg.BagMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
