// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerMsg.proto

package com.su.msg;

public final class PlayerMsg {
  private PlayerMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MPlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MPlayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 花生
     * </pre>
     *
     * <code>optional int32 peanut = 3 [default = -1];</code>
     */
    boolean hasPeanut();
    /**
     * <pre>
     * 花生
     * </pre>
     *
     * <code>optional int32 peanut = 3 [default = -1];</code>
     */
    int getPeanut();

    /**
     * <pre>
     * 段位分
     * </pre>
     *
     * <code>optional int32 rankingScore = 4 [default = -1];</code>
     */
    boolean hasRankingScore();
    /**
     * <pre>
     * 段位分
     * </pre>
     *
     * <code>optional int32 rankingScore = 4 [default = -1];</code>
     */
    int getRankingScore();

    /**
     * <pre>
     * 段位
     * </pre>
     *
     * <code>optional int32 rankingStep = 5 [default = -1];</code>
     */
    boolean hasRankingStep();
    /**
     * <pre>
     * 段位
     * </pre>
     *
     * <code>optional int32 rankingStep = 5 [default = -1];</code>
     */
    int getRankingStep();
  }
  /**
   * <pre>
   * 玩家数据
   * </pre>
   *
   * Protobuf type {@code MPlayer}
   */
  public  static final class MPlayer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MPlayer)
      MPlayerOrBuilder {
    // Use MPlayer.newBuilder() to construct.
    private MPlayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MPlayer() {
      id_ = 0L;
      name_ = "";
      peanut_ = -1;
      rankingScore_ = -1;
      rankingStep_ = -1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MPlayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              peanut_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              rankingScore_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              rankingStep_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.PlayerMsg.internal_static_MPlayer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.PlayerMsg.internal_static_MPlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.PlayerMsg.MPlayer.class, com.su.msg.PlayerMsg.MPlayer.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PEANUT_FIELD_NUMBER = 3;
    private int peanut_;
    /**
     * <pre>
     * 花生
     * </pre>
     *
     * <code>optional int32 peanut = 3 [default = -1];</code>
     */
    public boolean hasPeanut() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 花生
     * </pre>
     *
     * <code>optional int32 peanut = 3 [default = -1];</code>
     */
    public int getPeanut() {
      return peanut_;
    }

    public static final int RANKINGSCORE_FIELD_NUMBER = 4;
    private int rankingScore_;
    /**
     * <pre>
     * 段位分
     * </pre>
     *
     * <code>optional int32 rankingScore = 4 [default = -1];</code>
     */
    public boolean hasRankingScore() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 段位分
     * </pre>
     *
     * <code>optional int32 rankingScore = 4 [default = -1];</code>
     */
    public int getRankingScore() {
      return rankingScore_;
    }

    public static final int RANKINGSTEP_FIELD_NUMBER = 5;
    private int rankingStep_;
    /**
     * <pre>
     * 段位
     * </pre>
     *
     * <code>optional int32 rankingStep = 5 [default = -1];</code>
     */
    public boolean hasRankingStep() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 段位
     * </pre>
     *
     * <code>optional int32 rankingStep = 5 [default = -1];</code>
     */
    public int getRankingStep() {
      return rankingStep_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, peanut_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, rankingScore_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, rankingStep_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, peanut_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, rankingScore_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, rankingStep_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.PlayerMsg.MPlayer)) {
        return super.equals(obj);
      }
      com.su.msg.PlayerMsg.MPlayer other = (com.su.msg.PlayerMsg.MPlayer) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasPeanut() == other.hasPeanut());
      if (hasPeanut()) {
        result = result && (getPeanut()
            == other.getPeanut());
      }
      result = result && (hasRankingScore() == other.hasRankingScore());
      if (hasRankingScore()) {
        result = result && (getRankingScore()
            == other.getRankingScore());
      }
      result = result && (hasRankingStep() == other.hasRankingStep());
      if (hasRankingStep()) {
        result = result && (getRankingStep()
            == other.getRankingStep());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasPeanut()) {
        hash = (37 * hash) + PEANUT_FIELD_NUMBER;
        hash = (53 * hash) + getPeanut();
      }
      if (hasRankingScore()) {
        hash = (37 * hash) + RANKINGSCORE_FIELD_NUMBER;
        hash = (53 * hash) + getRankingScore();
      }
      if (hasRankingStep()) {
        hash = (37 * hash) + RANKINGSTEP_FIELD_NUMBER;
        hash = (53 * hash) + getRankingStep();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.PlayerMsg.MPlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.MPlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.MPlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.MPlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.MPlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.MPlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.MPlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.MPlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.MPlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.MPlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.PlayerMsg.MPlayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 玩家数据
     * </pre>
     *
     * Protobuf type {@code MPlayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MPlayer)
        com.su.msg.PlayerMsg.MPlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.PlayerMsg.internal_static_MPlayer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.PlayerMsg.internal_static_MPlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.PlayerMsg.MPlayer.class, com.su.msg.PlayerMsg.MPlayer.Builder.class);
      }

      // Construct using com.su.msg.PlayerMsg.MPlayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        peanut_ = -1;
        bitField0_ = (bitField0_ & ~0x00000004);
        rankingScore_ = -1;
        bitField0_ = (bitField0_ & ~0x00000008);
        rankingStep_ = -1;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.PlayerMsg.internal_static_MPlayer_descriptor;
      }

      public com.su.msg.PlayerMsg.MPlayer getDefaultInstanceForType() {
        return com.su.msg.PlayerMsg.MPlayer.getDefaultInstance();
      }

      public com.su.msg.PlayerMsg.MPlayer build() {
        com.su.msg.PlayerMsg.MPlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.PlayerMsg.MPlayer buildPartial() {
        com.su.msg.PlayerMsg.MPlayer result = new com.su.msg.PlayerMsg.MPlayer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.peanut_ = peanut_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rankingScore_ = rankingScore_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.rankingStep_ = rankingStep_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.PlayerMsg.MPlayer) {
          return mergeFrom((com.su.msg.PlayerMsg.MPlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.PlayerMsg.MPlayer other) {
        if (other == com.su.msg.PlayerMsg.MPlayer.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPeanut()) {
          setPeanut(other.getPeanut());
        }
        if (other.hasRankingScore()) {
          setRankingScore(other.getRankingScore());
        }
        if (other.hasRankingStep()) {
          setRankingStep(other.getRankingStep());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.PlayerMsg.MPlayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.PlayerMsg.MPlayer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int peanut_ = -1;
      /**
       * <pre>
       * 花生
       * </pre>
       *
       * <code>optional int32 peanut = 3 [default = -1];</code>
       */
      public boolean hasPeanut() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 花生
       * </pre>
       *
       * <code>optional int32 peanut = 3 [default = -1];</code>
       */
      public int getPeanut() {
        return peanut_;
      }
      /**
       * <pre>
       * 花生
       * </pre>
       *
       * <code>optional int32 peanut = 3 [default = -1];</code>
       */
      public Builder setPeanut(int value) {
        bitField0_ |= 0x00000004;
        peanut_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 花生
       * </pre>
       *
       * <code>optional int32 peanut = 3 [default = -1];</code>
       */
      public Builder clearPeanut() {
        bitField0_ = (bitField0_ & ~0x00000004);
        peanut_ = -1;
        onChanged();
        return this;
      }

      private int rankingScore_ = -1;
      /**
       * <pre>
       * 段位分
       * </pre>
       *
       * <code>optional int32 rankingScore = 4 [default = -1];</code>
       */
      public boolean hasRankingScore() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 段位分
       * </pre>
       *
       * <code>optional int32 rankingScore = 4 [default = -1];</code>
       */
      public int getRankingScore() {
        return rankingScore_;
      }
      /**
       * <pre>
       * 段位分
       * </pre>
       *
       * <code>optional int32 rankingScore = 4 [default = -1];</code>
       */
      public Builder setRankingScore(int value) {
        bitField0_ |= 0x00000008;
        rankingScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 段位分
       * </pre>
       *
       * <code>optional int32 rankingScore = 4 [default = -1];</code>
       */
      public Builder clearRankingScore() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rankingScore_ = -1;
        onChanged();
        return this;
      }

      private int rankingStep_ = -1;
      /**
       * <pre>
       * 段位
       * </pre>
       *
       * <code>optional int32 rankingStep = 5 [default = -1];</code>
       */
      public boolean hasRankingStep() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * 段位
       * </pre>
       *
       * <code>optional int32 rankingStep = 5 [default = -1];</code>
       */
      public int getRankingStep() {
        return rankingStep_;
      }
      /**
       * <pre>
       * 段位
       * </pre>
       *
       * <code>optional int32 rankingStep = 5 [default = -1];</code>
       */
      public Builder setRankingStep(int value) {
        bitField0_ |= 0x00000010;
        rankingStep_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 段位
       * </pre>
       *
       * <code>optional int32 rankingStep = 5 [default = -1];</code>
       */
      public Builder clearRankingStep() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rankingStep_ = -1;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MPlayer)
    }

    // @@protoc_insertion_point(class_scope:MPlayer)
    private static final com.su.msg.PlayerMsg.MPlayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.PlayerMsg.MPlayer();
    }

    public static com.su.msg.PlayerMsg.MPlayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MPlayer>
        PARSER = new com.google.protobuf.AbstractParser<MPlayer>() {
      public MPlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MPlayer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MPlayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MPlayer> getParserForType() {
      return PARSER;
    }

    public com.su.msg.PlayerMsg.MPlayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NUpdatePlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NUpdatePlayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .MPlayer player = 1;</code>
     */
    boolean hasPlayer();
    /**
     * <code>optional .MPlayer player = 1;</code>
     */
    com.su.msg.PlayerMsg.MPlayer getPlayer();
    /**
     * <code>optional .MPlayer player = 1;</code>
     */
    com.su.msg.PlayerMsg.MPlayerOrBuilder getPlayerOrBuilder();
  }
  /**
   * <pre>
   * 玩家数据更新通知
   * </pre>
   *
   * Protobuf type {@code NUpdatePlayer}
   */
  public  static final class NUpdatePlayer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NUpdatePlayer)
      NUpdatePlayerOrBuilder {
    // Use NUpdatePlayer.newBuilder() to construct.
    private NUpdatePlayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NUpdatePlayer() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NUpdatePlayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.su.msg.PlayerMsg.MPlayer.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = player_.toBuilder();
              }
              player_ = input.readMessage(com.su.msg.PlayerMsg.MPlayer.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(player_);
                player_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.PlayerMsg.internal_static_NUpdatePlayer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.PlayerMsg.internal_static_NUpdatePlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.PlayerMsg.NUpdatePlayer.class, com.su.msg.PlayerMsg.NUpdatePlayer.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYER_FIELD_NUMBER = 1;
    private com.su.msg.PlayerMsg.MPlayer player_;
    /**
     * <code>optional .MPlayer player = 1;</code>
     */
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .MPlayer player = 1;</code>
     */
    public com.su.msg.PlayerMsg.MPlayer getPlayer() {
      return player_ == null ? com.su.msg.PlayerMsg.MPlayer.getDefaultInstance() : player_;
    }
    /**
     * <code>optional .MPlayer player = 1;</code>
     */
    public com.su.msg.PlayerMsg.MPlayerOrBuilder getPlayerOrBuilder() {
      return player_ == null ? com.su.msg.PlayerMsg.MPlayer.getDefaultInstance() : player_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getPlayer());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlayer());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.PlayerMsg.NUpdatePlayer)) {
        return super.equals(obj);
      }
      com.su.msg.PlayerMsg.NUpdatePlayer other = (com.su.msg.PlayerMsg.NUpdatePlayer) obj;

      boolean result = true;
      result = result && (hasPlayer() == other.hasPlayer());
      if (hasPlayer()) {
        result = result && getPlayer()
            .equals(other.getPlayer());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlayer()) {
        hash = (37 * hash) + PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getPlayer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.PlayerMsg.NUpdatePlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.NUpdatePlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.NUpdatePlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.NUpdatePlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.NUpdatePlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.NUpdatePlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.NUpdatePlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.NUpdatePlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.NUpdatePlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.NUpdatePlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.PlayerMsg.NUpdatePlayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 玩家数据更新通知
     * </pre>
     *
     * Protobuf type {@code NUpdatePlayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NUpdatePlayer)
        com.su.msg.PlayerMsg.NUpdatePlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.PlayerMsg.internal_static_NUpdatePlayer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.PlayerMsg.internal_static_NUpdatePlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.PlayerMsg.NUpdatePlayer.class, com.su.msg.PlayerMsg.NUpdatePlayer.Builder.class);
      }

      // Construct using com.su.msg.PlayerMsg.NUpdatePlayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlayerFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (playerBuilder_ == null) {
          player_ = null;
        } else {
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.PlayerMsg.internal_static_NUpdatePlayer_descriptor;
      }

      public com.su.msg.PlayerMsg.NUpdatePlayer getDefaultInstanceForType() {
        return com.su.msg.PlayerMsg.NUpdatePlayer.getDefaultInstance();
      }

      public com.su.msg.PlayerMsg.NUpdatePlayer build() {
        com.su.msg.PlayerMsg.NUpdatePlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.PlayerMsg.NUpdatePlayer buildPartial() {
        com.su.msg.PlayerMsg.NUpdatePlayer result = new com.su.msg.PlayerMsg.NUpdatePlayer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (playerBuilder_ == null) {
          result.player_ = player_;
        } else {
          result.player_ = playerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.PlayerMsg.NUpdatePlayer) {
          return mergeFrom((com.su.msg.PlayerMsg.NUpdatePlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.PlayerMsg.NUpdatePlayer other) {
        if (other == com.su.msg.PlayerMsg.NUpdatePlayer.getDefaultInstance()) return this;
        if (other.hasPlayer()) {
          mergePlayer(other.getPlayer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.PlayerMsg.NUpdatePlayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.PlayerMsg.NUpdatePlayer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.su.msg.PlayerMsg.MPlayer player_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.su.msg.PlayerMsg.MPlayer, com.su.msg.PlayerMsg.MPlayer.Builder, com.su.msg.PlayerMsg.MPlayerOrBuilder> playerBuilder_;
      /**
       * <code>optional .MPlayer player = 1;</code>
       */
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .MPlayer player = 1;</code>
       */
      public com.su.msg.PlayerMsg.MPlayer getPlayer() {
        if (playerBuilder_ == null) {
          return player_ == null ? com.su.msg.PlayerMsg.MPlayer.getDefaultInstance() : player_;
        } else {
          return playerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .MPlayer player = 1;</code>
       */
      public Builder setPlayer(com.su.msg.PlayerMsg.MPlayer value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          player_ = value;
          onChanged();
        } else {
          playerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .MPlayer player = 1;</code>
       */
      public Builder setPlayer(
          com.su.msg.PlayerMsg.MPlayer.Builder builderForValue) {
        if (playerBuilder_ == null) {
          player_ = builderForValue.build();
          onChanged();
        } else {
          playerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .MPlayer player = 1;</code>
       */
      public Builder mergePlayer(com.su.msg.PlayerMsg.MPlayer value) {
        if (playerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              player_ != null &&
              player_ != com.su.msg.PlayerMsg.MPlayer.getDefaultInstance()) {
            player_ =
              com.su.msg.PlayerMsg.MPlayer.newBuilder(player_).mergeFrom(value).buildPartial();
          } else {
            player_ = value;
          }
          onChanged();
        } else {
          playerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .MPlayer player = 1;</code>
       */
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          player_ = null;
          onChanged();
        } else {
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .MPlayer player = 1;</code>
       */
      public com.su.msg.PlayerMsg.MPlayer.Builder getPlayerBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPlayerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .MPlayer player = 1;</code>
       */
      public com.su.msg.PlayerMsg.MPlayerOrBuilder getPlayerOrBuilder() {
        if (playerBuilder_ != null) {
          return playerBuilder_.getMessageOrBuilder();
        } else {
          return player_ == null ?
              com.su.msg.PlayerMsg.MPlayer.getDefaultInstance() : player_;
        }
      }
      /**
       * <code>optional .MPlayer player = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.su.msg.PlayerMsg.MPlayer, com.su.msg.PlayerMsg.MPlayer.Builder, com.su.msg.PlayerMsg.MPlayerOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.su.msg.PlayerMsg.MPlayer, com.su.msg.PlayerMsg.MPlayer.Builder, com.su.msg.PlayerMsg.MPlayerOrBuilder>(
                  getPlayer(),
                  getParentForChildren(),
                  isClean());
          player_ = null;
        }
        return playerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NUpdatePlayer)
    }

    // @@protoc_insertion_point(class_scope:NUpdatePlayer)
    private static final com.su.msg.PlayerMsg.NUpdatePlayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.PlayerMsg.NUpdatePlayer();
    }

    public static com.su.msg.PlayerMsg.NUpdatePlayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NUpdatePlayer>
        PARSER = new com.google.protobuf.AbstractParser<NUpdatePlayer>() {
      public NUpdatePlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NUpdatePlayer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NUpdatePlayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NUpdatePlayer> getParserForType() {
      return PARSER;
    }

    public com.su.msg.PlayerMsg.NUpdatePlayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MPlayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MPlayer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NUpdatePlayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NUpdatePlayer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PlayerMsg.proto\"j\n\007MPlayer\022\n\n\002id\030\001 \001(\003" +
      "\022\014\n\004name\030\002 \001(\t\022\022\n\006peanut\030\003 \001(\005:\002-1\022\030\n\014ra" +
      "nkingScore\030\004 \001(\005:\002-1\022\027\n\013rankingStep\030\005 \001(" +
      "\005:\002-1\")\n\rNUpdatePlayer\022\030\n\006player\030\001 \001(\0132\010" +
      ".MPlayerB\014\n\ncom.su.msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MPlayer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MPlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MPlayer_descriptor,
        new java.lang.String[] { "Id", "Name", "Peanut", "RankingScore", "RankingStep", });
    internal_static_NUpdatePlayer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NUpdatePlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NUpdatePlayer_descriptor,
        new java.lang.String[] { "Player", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
