/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Load from "./action/Load"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1512;
    static height:number=918;
    static scaleMode:string="noscale";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Load.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("action/Load.ts",Load);
    }
}
GameConfig.init();