// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Common.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace com.su.msg
{

    [global::ProtoBuf.ProtoContract(Name = @"Error_")]
    public partial class Error : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorCode
        {
            get { return __pbn__errorCode.GetValueOrDefault(); }
            set { __pbn__errorCode = value; }
        }
        public bool ShouldSerializeerrorCode() => __pbn__errorCode != null;
        public void ReseterrorCode() => __pbn__errorCode = null;
        private int? __pbn__errorCode;

        [global::ProtoBuf.ProtoMember(2, Name = @"parameters")]
        public global::System.Collections.Generic.List<string> Parameters { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"CMD")]
    public partial class Cmd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int cmd
        {
            get { return __pbn__cmd.GetValueOrDefault(); }
            set { __pbn__cmd = value; }
        }
        public bool ShouldSerializecmd() => __pbn__cmd != null;
        public void Resetcmd() => __pbn__cmd = null;
        private int? __pbn__cmd;

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public int Type
        {
            get { return __pbn__Type.GetValueOrDefault(); }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

        [global::ProtoBuf.ProtoMember(3)]
        public int sysId
        {
            get { return __pbn__sysId.GetValueOrDefault(); }
            set { __pbn__sysId = value; }
        }
        public bool ShouldSerializesysId() => __pbn__sysId != null;
        public void ResetsysId() => __pbn__sysId = null;
        private int? __pbn__sysId;

        [global::ProtoBuf.ProtoMember(4, Name = @"count")]
        public int Count
        {
            get { return __pbn__Count.GetValueOrDefault(); }
            set { __pbn__Count = value; }
        }
        public bool ShouldSerializeCount() => __pbn__Count != null;
        public void ResetCount() => __pbn__Count = null;
        private int? __pbn__Count;

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
