// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Login.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace com.su.msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Login : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account
        {
            get { return __pbn__Account ?? ""; }
            set { __pbn__Account = value; }
        }
        public bool ShouldSerializeAccount() => __pbn__Account != null;
        public void ResetAccount() => __pbn__Account = null;
        private string __pbn__Account;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

    }

    [global::ProtoBuf.ProtoContract(Name = @"Login_")]
    public partial class Login : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player")]
        public Player Player { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"grid")]
        public global::System.Collections.Generic.List<Grid> Grids { get; } = new global::System.Collections.Generic.List<Grid>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
