// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MatchSite.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace com.su.msg
{

    [global::ProtoBuf.ProtoContract(Name = @"_MatchSite")]
    public partial class MatchSite : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int siteId
        {
            get { return __pbn__siteId.GetValueOrDefault(); }
            set { __pbn__siteId = value; }
        }
        public bool ShouldSerializesiteId() => __pbn__siteId != null;
        public void ResetsiteId() => __pbn__siteId = null;
        private int? __pbn__siteId;

        [global::ProtoBuf.ProtoMember(2)]
        public int playerNum
        {
            get { return __pbn__playerNum.GetValueOrDefault(); }
            set { __pbn__playerNum = value; }
        }
        public bool ShouldSerializeplayerNum() => __pbn__playerNum != null;
        public void ResetplayerNum() => __pbn__playerNum = null;
        private int? __pbn__playerNum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Match : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int siteId
        {
            get { return __pbn__siteId.GetValueOrDefault(); }
            set { __pbn__siteId = value; }
        }
        public bool ShouldSerializesiteId() => __pbn__siteId != null;
        public void ResetsiteId() => __pbn__siteId = null;
        private int? __pbn__siteId;

    }

    [global::ProtoBuf.ProtoContract(Name = @"Match_")]
    public partial class Match : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelMatch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int siteId
        {
            get { return __pbn__siteId.GetValueOrDefault(); }
            set { __pbn__siteId = value; }
        }
        public bool ShouldSerializesiteId() => __pbn__siteId != null;
        public void ResetsiteId() => __pbn__siteId = null;
        private int? __pbn__siteId;

    }

    [global::ProtoBuf.ProtoContract(Name = @"CancelMatch_")]
    public partial class CancelMatch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMatchSite : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int siteType
        {
            get { return __pbn__siteType.GetValueOrDefault(); }
            set { __pbn__siteType = value; }
        }
        public bool ShouldSerializesiteType() => __pbn__siteType != null;
        public void ResetsiteType() => __pbn__siteType = null;
        private int? __pbn__siteType;

    }

    [global::ProtoBuf.ProtoContract(Name = @"GetMatchSite_")]
    public partial class GetMatchSite : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"matchSite")]
        public global::System.Collections.Generic.List<MatchSite> matchSites { get; } = new global::System.Collections.Generic.List<MatchSite>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
