// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Table.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace com.su.msg
{

    [global::ProtoBuf.ProtoContract(Name = @"_Card")]
    public partial class Card : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value")]
        public int Value
        {
            get { return __pbn__Value.GetValueOrDefault(); }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private int? __pbn__Value;

        [global::ProtoBuf.ProtoMember(2, Name = @"suit")]
        public int Suit
        {
            get { return __pbn__Suit.GetValueOrDefault(); }
            set { __pbn__Suit = value; }
        }
        public bool ShouldSerializeSuit() => __pbn__Suit != null;
        public void ResetSuit() => __pbn__Suit = null;
        private int? __pbn__Suit;

    }

    [global::ProtoBuf.ProtoContract(Name = @"_GamePlayer")]
    public partial class GamePlayer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public long Id
        {
            get { return __pbn__Id ?? -1; }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private long? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"handCard")]
        public global::System.Collections.Generic.List<Card> handCards { get; } = new global::System.Collections.Generic.List<Card>();

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int cardNum
        {
            get { return __pbn__cardNum ?? -1; }
            set { __pbn__cardNum = value; }
        }
        public bool ShouldSerializecardNum() => __pbn__cardNum != null;
        public void ResetcardNum() => __pbn__cardNum = null;
        private int? __pbn__cardNum;

        [global::ProtoBuf.ProtoMember(4, Name = @"team")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int Team
        {
            get { return __pbn__Team ?? -1; }
            set { __pbn__Team = value; }
        }
        public bool ShouldSerializeTeam() => __pbn__Team != null;
        public void ResetTeam() => __pbn__Team = null;
        private int? __pbn__Team;

        [global::ProtoBuf.ProtoMember(5, Name = @"multiple")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int Multiple
        {
            get { return __pbn__Multiple ?? -1; }
            set { __pbn__Multiple = value; }
        }
        public bool ShouldSerializeMultiple() => __pbn__Multiple != null;
        public void ResetMultiple() => __pbn__Multiple = null;
        private int? __pbn__Multiple;

        [global::ProtoBuf.ProtoMember(6, Name = @"score")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int Score
        {
            get { return __pbn__Score ?? -1; }
            set { __pbn__Score = value; }
        }
        public bool ShouldSerializeScore() => __pbn__Score != null;
        public void ResetScore() => __pbn__Score = null;
        private int? __pbn__Score;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int isAuto
        {
            get { return __pbn__isAuto ?? -1; }
            set { __pbn__isAuto = value; }
        }
        public bool ShouldSerializeisAuto() => __pbn__isAuto != null;
        public void ResetisAuto() => __pbn__isAuto = null;
        private int? __pbn__isAuto;

        [global::ProtoBuf.ProtoMember(8, Name = @"state")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int State
        {
            get { return __pbn__State ?? -1; }
            set { __pbn__State = value; }
        }
        public bool ShouldSerializeState() => __pbn__State != null;
        public void ResetState() => __pbn__State = null;
        private int? __pbn__State;

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public long opTime
        {
            get { return __pbn__opTime ?? -1; }
            set { __pbn__opTime = value; }
        }
        public bool ShouldSerializeopTime() => __pbn__opTime != null;
        public void ResetopTime() => __pbn__opTime = null;
        private long? __pbn__opTime;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int contestScore
        {
            get { return __pbn__contestScore ?? -1; }
            set { __pbn__contestScore = value; }
        }
        public bool ShouldSerializecontestScore() => __pbn__contestScore != null;
        public void ResetcontestScore() => __pbn__contestScore = null;
        private int? __pbn__contestScore;

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int isQuit
        {
            get { return __pbn__isQuit ?? -1; }
            set { __pbn__isQuit = value; }
        }
        public bool ShouldSerializeisQuit() => __pbn__isQuit != null;
        public void ResetisQuit() => __pbn__isQuit = null;
        private int? __pbn__isQuit;

    }

    [global::ProtoBuf.ProtoContract(Name = @"_Table")]
    public partial class Table : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player")]
        public global::System.Collections.Generic.List<GamePlayer> Players { get; } = new global::System.Collections.Generic.List<GamePlayer>();

        [global::ProtoBuf.ProtoMember(2, Name = @"multiple")]
        public int[] Multiples { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"state")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int State
        {
            get { return __pbn__State ?? -1; }
            set { __pbn__State = value; }
        }
        public bool ShouldSerializeState() => __pbn__State != null;
        public void ResetState() => __pbn__State = null;
        private int? __pbn__State;

        [global::ProtoBuf.ProtoMember(4, Name = @"lastCard")]
        public global::System.Collections.Generic.List<Card> lastCards { get; } = new global::System.Collections.Generic.List<Card>();

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int lastCardType
        {
            get { return __pbn__lastCardType ?? -1; }
            set { __pbn__lastCardType = value; }
        }
        public bool ShouldSerializelastCardType() => __pbn__lastCardType != null;
        public void ResetlastCardType() => __pbn__lastCardType = null;
        private int? __pbn__lastCardType;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int lastOp
        {
            get { return __pbn__lastOp ?? -1; }
            set { __pbn__lastOp = value; }
        }
        public bool ShouldSerializelastOp() => __pbn__lastOp != null;
        public void ResetlastOp() => __pbn__lastOp = null;
        private int? __pbn__lastOp;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int roundScore
        {
            get { return __pbn__roundScore ?? -1; }
            set { __pbn__roundScore = value; }
        }
        public bool ShouldSerializeroundScore() => __pbn__roundScore != null;
        public void ResetroundScore() => __pbn__roundScore = null;
        private int? __pbn__roundScore;

        [global::ProtoBuf.ProtoMember(8)]
        public Card callCard { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int callType
        {
            get { return __pbn__callType ?? -1; }
            set { __pbn__callType = value; }
        }
        public bool ShouldSerializecallType() => __pbn__callType != null;
        public void ResetcallType() => __pbn__callType = null;
        private int? __pbn__callType;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int callOp
        {
            get { return __pbn__callOp ?? -1; }
            set { __pbn__callOp = value; }
        }
        public bool ShouldSerializecallOp() => __pbn__callOp != null;
        public void ResetcallOp() => __pbn__callOp = null;
        private int? __pbn__callOp;

        [global::ProtoBuf.ProtoMember(11, Name = @"dealer")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int Dealer
        {
            get { return __pbn__Dealer ?? -1; }
            set { __pbn__Dealer = value; }
        }
        public bool ShouldSerializeDealer() => __pbn__Dealer != null;
        public void ResetDealer() => __pbn__Dealer = null;
        private int? __pbn__Dealer;

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public long waitTime
        {
            get { return __pbn__waitTime ?? -1; }
            set { __pbn__waitTime = value; }
        }
        public bool ShouldSerializewaitTime() => __pbn__waitTime != null;
        public void ResetwaitTime() => __pbn__waitTime = null;
        private long? __pbn__waitTime;

        [global::ProtoBuf.ProtoMember(13, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int Type
        {
            get { return __pbn__Type ?? -1; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Call : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int callType
        {
            get { return __pbn__callType.GetValueOrDefault(); }
            set { __pbn__callType = value; }
        }
        public bool ShouldSerializecallType() => __pbn__callType != null;
        public void ResetcallType() => __pbn__callType = null;
        private int? __pbn__callType;

        [global::ProtoBuf.ProtoMember(2)]
        public int cardIndex
        {
            get { return __pbn__cardIndex.GetValueOrDefault(); }
            set { __pbn__cardIndex = value; }
        }
        public bool ShouldSerializecardIndex() => __pbn__cardIndex != null;
        public void ResetcardIndex() => __pbn__cardIndex = null;
        private int? __pbn__cardIndex;

    }

    [global::ProtoBuf.ProtoContract(Name = @"Call_")]
    public partial class Call : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Draw : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int cardType
        {
            get { return __pbn__cardType.GetValueOrDefault(); }
            set { __pbn__cardType = value; }
        }
        public bool ShouldSerializecardType() => __pbn__cardType != null;
        public void ResetcardType() => __pbn__cardType = null;
        private int? __pbn__cardType;

        [global::ProtoBuf.ProtoMember(2)]
        public int[] cardIndexs { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"Draw_")]
    public partial class Draw : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Check : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"Check_")]
    public partial class Check : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Ready : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"Ready_")]
    public partial class Ready : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Quit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"Quit_")]
    public partial class Quit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Double : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"Double_")]
    public partial class Double : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Auto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int isAuto
        {
            get { return __pbn__isAuto.GetValueOrDefault(); }
            set { __pbn__isAuto = value; }
        }
        public bool ShouldSerializeisAuto() => __pbn__isAuto != null;
        public void ResetisAuto() => __pbn__isAuto = null;
        private int? __pbn__isAuto;

    }

    [global::ProtoBuf.ProtoContract(Name = @"Auto_")]
    public partial class Auto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Reconn : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"Reconn_")]
    public partial class Reconn : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"UpdateGamePlayer_")]
    public partial class UpdateGamePlayer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gamePlayer")]
        public global::System.Collections.Generic.List<GamePlayer> gamePlayers { get; } = new global::System.Collections.Generic.List<GamePlayer>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"UpdateTable_")]
    public partial class UpdateTable : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table")]
        public Table Table { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"_GamePlayerResult")]
    public partial class GamePlayerResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"multiple")]
        public int Multiple
        {
            get { return __pbn__Multiple.GetValueOrDefault(); }
            set { __pbn__Multiple = value; }
        }
        public bool ShouldSerializeMultiple() => __pbn__Multiple != null;
        public void ResetMultiple() => __pbn__Multiple = null;
        private int? __pbn__Multiple;

        [global::ProtoBuf.ProtoMember(2, Name = @"peanut")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int Peanut
        {
            get { return __pbn__Peanut ?? -1; }
            set { __pbn__Peanut = value; }
        }
        public bool ShouldSerializePeanut() => __pbn__Peanut != null;
        public void ResetPeanut() => __pbn__Peanut = null;
        private int? __pbn__Peanut;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int rankingScore
        {
            get { return __pbn__rankingScore ?? -1; }
            set { __pbn__rankingScore = value; }
        }
        public bool ShouldSerializerankingScore() => __pbn__rankingScore != null;
        public void ResetrankingScore() => __pbn__rankingScore = null;
        private int? __pbn__rankingScore;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int contestScore
        {
            get { return __pbn__contestScore ?? -1; }
            set { __pbn__contestScore = value; }
        }
        public bool ShouldSerializecontestScore() => __pbn__contestScore != null;
        public void ResetcontestScore() => __pbn__contestScore = null;
        private int? __pbn__contestScore;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public long playerId
        {
            get { return __pbn__playerId ?? -1; }
            set { __pbn__playerId = value; }
        }
        public bool ShouldSerializeplayerId() => __pbn__playerId != null;
        public void ResetplayerId() => __pbn__playerId = null;
        private long? __pbn__playerId;

    }

    [global::ProtoBuf.ProtoContract(Name = @"TableResult_")]
    public partial class TableResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int baseScore
        {
            get { return __pbn__baseScore.GetValueOrDefault(); }
            set { __pbn__baseScore = value; }
        }
        public bool ShouldSerializebaseScore() => __pbn__baseScore != null;
        public void ResetbaseScore() => __pbn__baseScore = null;
        private int? __pbn__baseScore;

        [global::ProtoBuf.ProtoMember(2)]
        public int winTeam
        {
            get { return __pbn__winTeam.GetValueOrDefault(); }
            set { __pbn__winTeam = value; }
        }
        public bool ShouldSerializewinTeam() => __pbn__winTeam != null;
        public void ResetwinTeam() => __pbn__winTeam = null;
        private int? __pbn__winTeam;

        [global::ProtoBuf.ProtoMember(3, Name = @"playerResult")]
        public global::System.Collections.Generic.List<GamePlayerResult> playerResults { get; } = new global::System.Collections.Generic.List<GamePlayerResult>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
