// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: XunBaoMsg.proto

#pragma warning disable 1591, 0612, 3021
namespace Assets.Scripts.Proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class XunBaoMo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public XunBaoMo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type
        {
            get { return __pbn__Type.GetValueOrDefault(); }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType()
        {
            return __pbn__Type != null;
        }
        public void ResetType()
        {
            __pbn__Type = null;
        }
        private int? __pbn__Type;

        [global::ProtoBuf.ProtoMember(2)]
        public long nextTime
        {
            get { return __pbn__nextTime.GetValueOrDefault(); }
            set { __pbn__nextTime = value; }
        }
        public bool ShouldSerializenextTime()
        {
            return __pbn__nextTime != null;
        }
        public void ResetnextTime()
        {
            __pbn__nextTime = null;
        }
        private long? __pbn__nextTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetXunBao : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public GetXunBao()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetXunBaoTo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public GetXunBaoTo()
        {
            xunBaoes = new global::System.Collections.Generic.List<XunBaoMo>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"xunBao")]
        public global::System.Collections.Generic.List<XunBaoMo> xunBaoes { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class XunBao : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public XunBao()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type
        {
            get { return __pbn__Type.GetValueOrDefault(); }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType()
        {
            return __pbn__Type != null;
        }
        public void ResetType()
        {
            __pbn__Type = null;
        }
        private int? __pbn__Type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class XunBaoTo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public XunBaoTo()
        {
            Rewards = new global::System.Collections.Generic.List<RewardMo>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"reward")]
        public global::System.Collections.Generic.List<RewardMo> Rewards { get; private set; }

    }

}

#pragma warning restore 1591, 0612, 3021
