// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: RoleMsg.proto

#pragma warning disable 1591, 0612, 3021
namespace Assets.Scripts.Proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleMo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RoleMo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"rid")]
        public int Rid
        {
            get { return __pbn__Rid.GetValueOrDefault(); }
            set { __pbn__Rid = value; }
        }
        public bool ShouldSerializeRid()
        {
            return __pbn__Rid != null;
        }
        public void ResetRid()
        {
            __pbn__Rid = null;
        }
        private int? __pbn__Rid;

        [global::ProtoBuf.ProtoMember(2, Name = @"exp")]
        public int Exp
        {
            get { return __pbn__Exp.GetValueOrDefault(); }
            set { __pbn__Exp = value; }
        }
        public bool ShouldSerializeExp()
        {
            return __pbn__Exp != null;
        }
        public void ResetExp()
        {
            __pbn__Exp = null;
        }
        private int? __pbn__Exp;

        [global::ProtoBuf.ProtoMember(3)]
        public int effType
        {
            get { return __pbn__effType.GetValueOrDefault(); }
            set { __pbn__effType = value; }
        }
        public bool ShouldSerializeeffType()
        {
            return __pbn__effType != null;
        }
        public void ReseteffType()
        {
            __pbn__effType = null;
        }
        private int? __pbn__effType;

        [global::ProtoBuf.ProtoMember(4)]
        public long effValue
        {
            get { return __pbn__effValue.GetValueOrDefault(); }
            set { __pbn__effValue = value; }
        }
        public bool ShouldSerializeeffValue()
        {
            return __pbn__effValue != null;
        }
        public void ReseteffValue()
        {
            __pbn__effValue = null;
        }
        private long? __pbn__effValue;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRole : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public GetRole()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRoleTo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public GetRoleTo()
        {
            Roles = new global::System.Collections.Generic.List<RoleMo>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"role")]
        public global::System.Collections.Generic.List<RoleMo> Roles { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpRole : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public UpRole()
        {
            Costs = new global::System.Collections.Generic.Dictionary<int, int>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"rid")]
        public int Rid
        {
            get { return __pbn__Rid.GetValueOrDefault(); }
            set { __pbn__Rid = value; }
        }
        public bool ShouldSerializeRid()
        {
            return __pbn__Rid != null;
        }
        public void ResetRid()
        {
            __pbn__Rid = null;
        }
        private int? __pbn__Rid;

        [global::ProtoBuf.ProtoMember(2, Name = @"cost")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> Costs { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpRoleTo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public UpRoleTo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleNo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RoleNo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"role")]
        public RoleMo Role { get; set; }

    }

}

#pragma warning restore 1591, 0612, 3021
