// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerMsg.proto

package com.su.msg;

public final class PlayerMsg {
  private PlayerMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerMoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg.PlayerMo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    boolean hasAccount();
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    java.lang.String getAccount();
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>optional string avatar = 3;</code>
     */
    boolean hasAvatar();
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>optional string avatar = 3;</code>
     */
    java.lang.String getAvatar();
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>optional string avatar = 3;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    boolean hasName();
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional int32 gender = 5;</code>
     */
    boolean hasGender();
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional int32 gender = 5;</code>
     */
    int getGender();

    /**
     * <pre>
     * 豆子
     * </pre>
     *
     * <code>optional int32 bean = 6;</code>
     */
    boolean hasBean();
    /**
     * <pre>
     * 豆子
     * </pre>
     *
     * <code>optional int32 bean = 6;</code>
     */
    int getBean();

    /**
     * <pre>
     * 钻石
     * </pre>
     *
     * <code>optional int32 diamond = 7;</code>
     */
    boolean hasDiamond();
    /**
     * <pre>
     * 钻石
     * </pre>
     *
     * <code>optional int32 diamond = 7;</code>
     */
    int getDiamond();
  }
  /**
   * <pre>
   * 玩家数据
   * </pre>
   *
   * Protobuf type {@code Msg.PlayerMo}
   */
  public  static final class PlayerMo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg.PlayerMo)
      PlayerMoOrBuilder {
    // Use PlayerMo.newBuilder() to construct.
    private PlayerMo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerMo() {
      id_ = 0L;
      account_ = "";
      avatar_ = "";
      name_ = "";
      gender_ = 0;
      bean_ = 0;
      diamond_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerMo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              account_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              avatar_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              name_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              gender_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              bean_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              diamond_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.PlayerMsg.internal_static_Msg_PlayerMo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.PlayerMsg.internal_static_Msg_PlayerMo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.PlayerMsg.PlayerMo.class, com.su.msg.PlayerMsg.PlayerMo.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private volatile java.lang.Object account_;
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 3;
    private volatile java.lang.Object avatar_;
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>optional string avatar = 3;</code>
     */
    public boolean hasAvatar() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>optional string avatar = 3;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          avatar_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>optional string avatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 名称
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 5;
    private int gender_;
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional int32 gender = 5;</code>
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional int32 gender = 5;</code>
     */
    public int getGender() {
      return gender_;
    }

    public static final int BEAN_FIELD_NUMBER = 6;
    private int bean_;
    /**
     * <pre>
     * 豆子
     * </pre>
     *
     * <code>optional int32 bean = 6;</code>
     */
    public boolean hasBean() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * 豆子
     * </pre>
     *
     * <code>optional int32 bean = 6;</code>
     */
    public int getBean() {
      return bean_;
    }

    public static final int DIAMOND_FIELD_NUMBER = 7;
    private int diamond_;
    /**
     * <pre>
     * 钻石
     * </pre>
     *
     * <code>optional int32 diamond = 7;</code>
     */
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * 钻石
     * </pre>
     *
     * <code>optional int32 diamond = 7;</code>
     */
    public int getDiamond() {
      return diamond_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, account_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, gender_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, bean_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, diamond_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, account_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, gender_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, bean_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, diamond_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.PlayerMsg.PlayerMo)) {
        return super.equals(obj);
      }
      com.su.msg.PlayerMsg.PlayerMo other = (com.su.msg.PlayerMsg.PlayerMo) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasAccount() == other.hasAccount());
      if (hasAccount()) {
        result = result && getAccount()
            .equals(other.getAccount());
      }
      result = result && (hasAvatar() == other.hasAvatar());
      if (hasAvatar()) {
        result = result && getAvatar()
            .equals(other.getAvatar());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasGender() == other.hasGender());
      if (hasGender()) {
        result = result && (getGender()
            == other.getGender());
      }
      result = result && (hasBean() == other.hasBean());
      if (hasBean()) {
        result = result && (getBean()
            == other.getBean());
      }
      result = result && (hasDiamond() == other.hasDiamond());
      if (hasDiamond()) {
        result = result && (getDiamond()
            == other.getDiamond());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasAccount()) {
        hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAccount().hashCode();
      }
      if (hasAvatar()) {
        hash = (37 * hash) + AVATAR_FIELD_NUMBER;
        hash = (53 * hash) + getAvatar().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasGender()) {
        hash = (37 * hash) + GENDER_FIELD_NUMBER;
        hash = (53 * hash) + getGender();
      }
      if (hasBean()) {
        hash = (37 * hash) + BEAN_FIELD_NUMBER;
        hash = (53 * hash) + getBean();
      }
      if (hasDiamond()) {
        hash = (37 * hash) + DIAMOND_FIELD_NUMBER;
        hash = (53 * hash) + getDiamond();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.PlayerMsg.PlayerMo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.PlayerMo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.PlayerMo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.PlayerMo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.PlayerMo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.PlayerMo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.PlayerMo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.PlayerMo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.PlayerMo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.PlayerMo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.PlayerMsg.PlayerMo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 玩家数据
     * </pre>
     *
     * Protobuf type {@code Msg.PlayerMo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg.PlayerMo)
        com.su.msg.PlayerMsg.PlayerMoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.PlayerMsg.internal_static_Msg_PlayerMo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.PlayerMsg.internal_static_Msg_PlayerMo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.PlayerMsg.PlayerMo.class, com.su.msg.PlayerMsg.PlayerMo.Builder.class);
      }

      // Construct using com.su.msg.PlayerMsg.PlayerMo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        avatar_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        gender_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        bean_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        diamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.PlayerMsg.internal_static_Msg_PlayerMo_descriptor;
      }

      public com.su.msg.PlayerMsg.PlayerMo getDefaultInstanceForType() {
        return com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance();
      }

      public com.su.msg.PlayerMsg.PlayerMo build() {
        com.su.msg.PlayerMsg.PlayerMo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.PlayerMsg.PlayerMo buildPartial() {
        com.su.msg.PlayerMsg.PlayerMo result = new com.su.msg.PlayerMsg.PlayerMo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.avatar_ = avatar_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.gender_ = gender_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bean_ = bean_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.diamond_ = diamond_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.PlayerMsg.PlayerMo) {
          return mergeFrom((com.su.msg.PlayerMsg.PlayerMo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.PlayerMsg.PlayerMo other) {
        if (other == com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAccount()) {
          bitField0_ |= 0x00000002;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasAvatar()) {
          bitField0_ |= 0x00000004;
          avatar_ = other.avatar_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000008;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        if (other.hasBean()) {
          setBean(other.getBean());
        }
        if (other.hasDiamond()) {
          setDiamond(other.getDiamond());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.PlayerMsg.PlayerMo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.PlayerMsg.PlayerMo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 2;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 2;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            account_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 2;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 2;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>optional string account = 2;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public boolean hasAvatar() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            avatar_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public Builder clearAvatar() {
        bitField0_ = (bitField0_ & ~0x00000004);
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>optional string avatar = 3;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        avatar_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 4;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 4;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>optional string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }

      private int gender_ ;
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional int32 gender = 5;</code>
       */
      public boolean hasGender() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional int32 gender = 5;</code>
       */
      public int getGender() {
        return gender_;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional int32 gender = 5;</code>
       */
      public Builder setGender(int value) {
        bitField0_ |= 0x00000010;
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional int32 gender = 5;</code>
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gender_ = 0;
        onChanged();
        return this;
      }

      private int bean_ ;
      /**
       * <pre>
       * 豆子
       * </pre>
       *
       * <code>optional int32 bean = 6;</code>
       */
      public boolean hasBean() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * 豆子
       * </pre>
       *
       * <code>optional int32 bean = 6;</code>
       */
      public int getBean() {
        return bean_;
      }
      /**
       * <pre>
       * 豆子
       * </pre>
       *
       * <code>optional int32 bean = 6;</code>
       */
      public Builder setBean(int value) {
        bitField0_ |= 0x00000020;
        bean_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 豆子
       * </pre>
       *
       * <code>optional int32 bean = 6;</code>
       */
      public Builder clearBean() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bean_ = 0;
        onChanged();
        return this;
      }

      private int diamond_ ;
      /**
       * <pre>
       * 钻石
       * </pre>
       *
       * <code>optional int32 diamond = 7;</code>
       */
      public boolean hasDiamond() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * 钻石
       * </pre>
       *
       * <code>optional int32 diamond = 7;</code>
       */
      public int getDiamond() {
        return diamond_;
      }
      /**
       * <pre>
       * 钻石
       * </pre>
       *
       * <code>optional int32 diamond = 7;</code>
       */
      public Builder setDiamond(int value) {
        bitField0_ |= 0x00000040;
        diamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 钻石
       * </pre>
       *
       * <code>optional int32 diamond = 7;</code>
       */
      public Builder clearDiamond() {
        bitField0_ = (bitField0_ & ~0x00000040);
        diamond_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg.PlayerMo)
    }

    // @@protoc_insertion_point(class_scope:Msg.PlayerMo)
    private static final com.su.msg.PlayerMsg.PlayerMo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.PlayerMsg.PlayerMo();
    }

    public static com.su.msg.PlayerMsg.PlayerMo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PlayerMo>
        PARSER = new com.google.protobuf.AbstractParser<PlayerMo>() {
      public PlayerMo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerMo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerMo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerMo> getParserForType() {
      return PARSER;
    }

    public com.su.msg.PlayerMsg.PlayerMo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetPlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg.GetPlayer)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 获取玩家数据
   * </pre>
   *
   * Protobuf type {@code Msg.GetPlayer}
   */
  public  static final class GetPlayer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg.GetPlayer)
      GetPlayerOrBuilder {
    // Use GetPlayer.newBuilder() to construct.
    private GetPlayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetPlayer() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetPlayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.PlayerMsg.internal_static_Msg_GetPlayer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.PlayerMsg.internal_static_Msg_GetPlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.PlayerMsg.GetPlayer.class, com.su.msg.PlayerMsg.GetPlayer.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.PlayerMsg.GetPlayer)) {
        return super.equals(obj);
      }
      com.su.msg.PlayerMsg.GetPlayer other = (com.su.msg.PlayerMsg.GetPlayer) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.PlayerMsg.GetPlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.GetPlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.GetPlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.GetPlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.GetPlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.GetPlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.GetPlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.GetPlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.GetPlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.GetPlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.PlayerMsg.GetPlayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 获取玩家数据
     * </pre>
     *
     * Protobuf type {@code Msg.GetPlayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg.GetPlayer)
        com.su.msg.PlayerMsg.GetPlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.PlayerMsg.internal_static_Msg_GetPlayer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.PlayerMsg.internal_static_Msg_GetPlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.PlayerMsg.GetPlayer.class, com.su.msg.PlayerMsg.GetPlayer.Builder.class);
      }

      // Construct using com.su.msg.PlayerMsg.GetPlayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.PlayerMsg.internal_static_Msg_GetPlayer_descriptor;
      }

      public com.su.msg.PlayerMsg.GetPlayer getDefaultInstanceForType() {
        return com.su.msg.PlayerMsg.GetPlayer.getDefaultInstance();
      }

      public com.su.msg.PlayerMsg.GetPlayer build() {
        com.su.msg.PlayerMsg.GetPlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.PlayerMsg.GetPlayer buildPartial() {
        com.su.msg.PlayerMsg.GetPlayer result = new com.su.msg.PlayerMsg.GetPlayer(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.PlayerMsg.GetPlayer) {
          return mergeFrom((com.su.msg.PlayerMsg.GetPlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.PlayerMsg.GetPlayer other) {
        if (other == com.su.msg.PlayerMsg.GetPlayer.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.PlayerMsg.GetPlayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.PlayerMsg.GetPlayer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg.GetPlayer)
    }

    // @@protoc_insertion_point(class_scope:Msg.GetPlayer)
    private static final com.su.msg.PlayerMsg.GetPlayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.PlayerMsg.GetPlayer();
    }

    public static com.su.msg.PlayerMsg.GetPlayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetPlayer>
        PARSER = new com.google.protobuf.AbstractParser<GetPlayer>() {
      public GetPlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetPlayer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetPlayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetPlayer> getParserForType() {
      return PARSER;
    }

    public com.su.msg.PlayerMsg.GetPlayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetPlayerToOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg.GetPlayerTo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    boolean hasPlayer();
    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    com.su.msg.PlayerMsg.PlayerMo getPlayer();
    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    com.su.msg.PlayerMsg.PlayerMoOrBuilder getPlayerOrBuilder();
  }
  /**
   * Protobuf type {@code Msg.GetPlayerTo}
   */
  public  static final class GetPlayerTo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg.GetPlayerTo)
      GetPlayerToOrBuilder {
    // Use GetPlayerTo.newBuilder() to construct.
    private GetPlayerTo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetPlayerTo() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetPlayerTo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.su.msg.PlayerMsg.PlayerMo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = player_.toBuilder();
              }
              player_ = input.readMessage(com.su.msg.PlayerMsg.PlayerMo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(player_);
                player_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.PlayerMsg.internal_static_Msg_GetPlayerTo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.PlayerMsg.internal_static_Msg_GetPlayerTo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.PlayerMsg.GetPlayerTo.class, com.su.msg.PlayerMsg.GetPlayerTo.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYER_FIELD_NUMBER = 1;
    private com.su.msg.PlayerMsg.PlayerMo player_;
    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    public com.su.msg.PlayerMsg.PlayerMo getPlayer() {
      return player_ == null ? com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance() : player_;
    }
    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    public com.su.msg.PlayerMsg.PlayerMoOrBuilder getPlayerOrBuilder() {
      return player_ == null ? com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance() : player_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getPlayer());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlayer());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.PlayerMsg.GetPlayerTo)) {
        return super.equals(obj);
      }
      com.su.msg.PlayerMsg.GetPlayerTo other = (com.su.msg.PlayerMsg.GetPlayerTo) obj;

      boolean result = true;
      result = result && (hasPlayer() == other.hasPlayer());
      if (hasPlayer()) {
        result = result && getPlayer()
            .equals(other.getPlayer());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlayer()) {
        hash = (37 * hash) + PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getPlayer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.PlayerMsg.GetPlayerTo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.GetPlayerTo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.GetPlayerTo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.GetPlayerTo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.GetPlayerTo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.GetPlayerTo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.GetPlayerTo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.GetPlayerTo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.GetPlayerTo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.GetPlayerTo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.PlayerMsg.GetPlayerTo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg.GetPlayerTo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg.GetPlayerTo)
        com.su.msg.PlayerMsg.GetPlayerToOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.PlayerMsg.internal_static_Msg_GetPlayerTo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.PlayerMsg.internal_static_Msg_GetPlayerTo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.PlayerMsg.GetPlayerTo.class, com.su.msg.PlayerMsg.GetPlayerTo.Builder.class);
      }

      // Construct using com.su.msg.PlayerMsg.GetPlayerTo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlayerFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (playerBuilder_ == null) {
          player_ = null;
        } else {
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.PlayerMsg.internal_static_Msg_GetPlayerTo_descriptor;
      }

      public com.su.msg.PlayerMsg.GetPlayerTo getDefaultInstanceForType() {
        return com.su.msg.PlayerMsg.GetPlayerTo.getDefaultInstance();
      }

      public com.su.msg.PlayerMsg.GetPlayerTo build() {
        com.su.msg.PlayerMsg.GetPlayerTo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.PlayerMsg.GetPlayerTo buildPartial() {
        com.su.msg.PlayerMsg.GetPlayerTo result = new com.su.msg.PlayerMsg.GetPlayerTo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (playerBuilder_ == null) {
          result.player_ = player_;
        } else {
          result.player_ = playerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.PlayerMsg.GetPlayerTo) {
          return mergeFrom((com.su.msg.PlayerMsg.GetPlayerTo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.PlayerMsg.GetPlayerTo other) {
        if (other == com.su.msg.PlayerMsg.GetPlayerTo.getDefaultInstance()) return this;
        if (other.hasPlayer()) {
          mergePlayer(other.getPlayer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.PlayerMsg.GetPlayerTo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.PlayerMsg.GetPlayerTo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.su.msg.PlayerMsg.PlayerMo player_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.su.msg.PlayerMsg.PlayerMo, com.su.msg.PlayerMsg.PlayerMo.Builder, com.su.msg.PlayerMsg.PlayerMoOrBuilder> playerBuilder_;
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public com.su.msg.PlayerMsg.PlayerMo getPlayer() {
        if (playerBuilder_ == null) {
          return player_ == null ? com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance() : player_;
        } else {
          return playerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public Builder setPlayer(com.su.msg.PlayerMsg.PlayerMo value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          player_ = value;
          onChanged();
        } else {
          playerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public Builder setPlayer(
          com.su.msg.PlayerMsg.PlayerMo.Builder builderForValue) {
        if (playerBuilder_ == null) {
          player_ = builderForValue.build();
          onChanged();
        } else {
          playerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public Builder mergePlayer(com.su.msg.PlayerMsg.PlayerMo value) {
        if (playerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              player_ != null &&
              player_ != com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance()) {
            player_ =
              com.su.msg.PlayerMsg.PlayerMo.newBuilder(player_).mergeFrom(value).buildPartial();
          } else {
            player_ = value;
          }
          onChanged();
        } else {
          playerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          player_ = null;
          onChanged();
        } else {
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public com.su.msg.PlayerMsg.PlayerMo.Builder getPlayerBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPlayerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public com.su.msg.PlayerMsg.PlayerMoOrBuilder getPlayerOrBuilder() {
        if (playerBuilder_ != null) {
          return playerBuilder_.getMessageOrBuilder();
        } else {
          return player_ == null ?
              com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance() : player_;
        }
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.su.msg.PlayerMsg.PlayerMo, com.su.msg.PlayerMsg.PlayerMo.Builder, com.su.msg.PlayerMsg.PlayerMoOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.su.msg.PlayerMsg.PlayerMo, com.su.msg.PlayerMsg.PlayerMo.Builder, com.su.msg.PlayerMsg.PlayerMoOrBuilder>(
                  getPlayer(),
                  getParentForChildren(),
                  isClean());
          player_ = null;
        }
        return playerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg.GetPlayerTo)
    }

    // @@protoc_insertion_point(class_scope:Msg.GetPlayerTo)
    private static final com.su.msg.PlayerMsg.GetPlayerTo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.PlayerMsg.GetPlayerTo();
    }

    public static com.su.msg.PlayerMsg.GetPlayerTo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetPlayerTo>
        PARSER = new com.google.protobuf.AbstractParser<GetPlayerTo>() {
      public GetPlayerTo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetPlayerTo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetPlayerTo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetPlayerTo> getParserForType() {
      return PARSER;
    }

    public com.su.msg.PlayerMsg.GetPlayerTo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdatePlayerNoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg.UpdatePlayerNo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    boolean hasPlayer();
    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    com.su.msg.PlayerMsg.PlayerMo getPlayer();
    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    com.su.msg.PlayerMsg.PlayerMoOrBuilder getPlayerOrBuilder();
  }
  /**
   * <pre>
   * 玩家数据更新通知
   * </pre>
   *
   * Protobuf type {@code Msg.UpdatePlayerNo}
   */
  public  static final class UpdatePlayerNo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg.UpdatePlayerNo)
      UpdatePlayerNoOrBuilder {
    // Use UpdatePlayerNo.newBuilder() to construct.
    private UpdatePlayerNo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdatePlayerNo() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdatePlayerNo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.su.msg.PlayerMsg.PlayerMo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = player_.toBuilder();
              }
              player_ = input.readMessage(com.su.msg.PlayerMsg.PlayerMo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(player_);
                player_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.PlayerMsg.internal_static_Msg_UpdatePlayerNo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.PlayerMsg.internal_static_Msg_UpdatePlayerNo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.PlayerMsg.UpdatePlayerNo.class, com.su.msg.PlayerMsg.UpdatePlayerNo.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYER_FIELD_NUMBER = 1;
    private com.su.msg.PlayerMsg.PlayerMo player_;
    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    public com.su.msg.PlayerMsg.PlayerMo getPlayer() {
      return player_ == null ? com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance() : player_;
    }
    /**
     * <code>optional .Msg.PlayerMo player = 1;</code>
     */
    public com.su.msg.PlayerMsg.PlayerMoOrBuilder getPlayerOrBuilder() {
      return player_ == null ? com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance() : player_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getPlayer());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlayer());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.PlayerMsg.UpdatePlayerNo)) {
        return super.equals(obj);
      }
      com.su.msg.PlayerMsg.UpdatePlayerNo other = (com.su.msg.PlayerMsg.UpdatePlayerNo) obj;

      boolean result = true;
      result = result && (hasPlayer() == other.hasPlayer());
      if (hasPlayer()) {
        result = result && getPlayer()
            .equals(other.getPlayer());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlayer()) {
        hash = (37 * hash) + PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getPlayer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.PlayerMsg.UpdatePlayerNo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.UpdatePlayerNo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.UpdatePlayerNo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.PlayerMsg.UpdatePlayerNo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.UpdatePlayerNo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.UpdatePlayerNo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.UpdatePlayerNo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.UpdatePlayerNo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.PlayerMsg.UpdatePlayerNo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.PlayerMsg.UpdatePlayerNo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.PlayerMsg.UpdatePlayerNo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 玩家数据更新通知
     * </pre>
     *
     * Protobuf type {@code Msg.UpdatePlayerNo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg.UpdatePlayerNo)
        com.su.msg.PlayerMsg.UpdatePlayerNoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.PlayerMsg.internal_static_Msg_UpdatePlayerNo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.PlayerMsg.internal_static_Msg_UpdatePlayerNo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.PlayerMsg.UpdatePlayerNo.class, com.su.msg.PlayerMsg.UpdatePlayerNo.Builder.class);
      }

      // Construct using com.su.msg.PlayerMsg.UpdatePlayerNo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlayerFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (playerBuilder_ == null) {
          player_ = null;
        } else {
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.PlayerMsg.internal_static_Msg_UpdatePlayerNo_descriptor;
      }

      public com.su.msg.PlayerMsg.UpdatePlayerNo getDefaultInstanceForType() {
        return com.su.msg.PlayerMsg.UpdatePlayerNo.getDefaultInstance();
      }

      public com.su.msg.PlayerMsg.UpdatePlayerNo build() {
        com.su.msg.PlayerMsg.UpdatePlayerNo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.PlayerMsg.UpdatePlayerNo buildPartial() {
        com.su.msg.PlayerMsg.UpdatePlayerNo result = new com.su.msg.PlayerMsg.UpdatePlayerNo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (playerBuilder_ == null) {
          result.player_ = player_;
        } else {
          result.player_ = playerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.PlayerMsg.UpdatePlayerNo) {
          return mergeFrom((com.su.msg.PlayerMsg.UpdatePlayerNo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.PlayerMsg.UpdatePlayerNo other) {
        if (other == com.su.msg.PlayerMsg.UpdatePlayerNo.getDefaultInstance()) return this;
        if (other.hasPlayer()) {
          mergePlayer(other.getPlayer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.PlayerMsg.UpdatePlayerNo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.PlayerMsg.UpdatePlayerNo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.su.msg.PlayerMsg.PlayerMo player_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.su.msg.PlayerMsg.PlayerMo, com.su.msg.PlayerMsg.PlayerMo.Builder, com.su.msg.PlayerMsg.PlayerMoOrBuilder> playerBuilder_;
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public com.su.msg.PlayerMsg.PlayerMo getPlayer() {
        if (playerBuilder_ == null) {
          return player_ == null ? com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance() : player_;
        } else {
          return playerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public Builder setPlayer(com.su.msg.PlayerMsg.PlayerMo value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          player_ = value;
          onChanged();
        } else {
          playerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public Builder setPlayer(
          com.su.msg.PlayerMsg.PlayerMo.Builder builderForValue) {
        if (playerBuilder_ == null) {
          player_ = builderForValue.build();
          onChanged();
        } else {
          playerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public Builder mergePlayer(com.su.msg.PlayerMsg.PlayerMo value) {
        if (playerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              player_ != null &&
              player_ != com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance()) {
            player_ =
              com.su.msg.PlayerMsg.PlayerMo.newBuilder(player_).mergeFrom(value).buildPartial();
          } else {
            player_ = value;
          }
          onChanged();
        } else {
          playerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          player_ = null;
          onChanged();
        } else {
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public com.su.msg.PlayerMsg.PlayerMo.Builder getPlayerBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPlayerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      public com.su.msg.PlayerMsg.PlayerMoOrBuilder getPlayerOrBuilder() {
        if (playerBuilder_ != null) {
          return playerBuilder_.getMessageOrBuilder();
        } else {
          return player_ == null ?
              com.su.msg.PlayerMsg.PlayerMo.getDefaultInstance() : player_;
        }
      }
      /**
       * <code>optional .Msg.PlayerMo player = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.su.msg.PlayerMsg.PlayerMo, com.su.msg.PlayerMsg.PlayerMo.Builder, com.su.msg.PlayerMsg.PlayerMoOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.su.msg.PlayerMsg.PlayerMo, com.su.msg.PlayerMsg.PlayerMo.Builder, com.su.msg.PlayerMsg.PlayerMoOrBuilder>(
                  getPlayer(),
                  getParentForChildren(),
                  isClean());
          player_ = null;
        }
        return playerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg.UpdatePlayerNo)
    }

    // @@protoc_insertion_point(class_scope:Msg.UpdatePlayerNo)
    private static final com.su.msg.PlayerMsg.UpdatePlayerNo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.PlayerMsg.UpdatePlayerNo();
    }

    public static com.su.msg.PlayerMsg.UpdatePlayerNo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UpdatePlayerNo>
        PARSER = new com.google.protobuf.AbstractParser<UpdatePlayerNo>() {
      public UpdatePlayerNo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdatePlayerNo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdatePlayerNo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdatePlayerNo> getParserForType() {
      return PARSER;
    }

    public com.su.msg.PlayerMsg.UpdatePlayerNo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_PlayerMo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_PlayerMo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_GetPlayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_GetPlayer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_GetPlayerTo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_GetPlayerTo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_UpdatePlayerNo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_UpdatePlayerNo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PlayerMsg.proto\022\003Msg\"t\n\010PlayerMo\022\n\n\002id" +
      "\030\001 \001(\003\022\017\n\007account\030\002 \001(\t\022\016\n\006avatar\030\003 \001(\t\022" +
      "\014\n\004name\030\004 \001(\t\022\016\n\006gender\030\005 \001(\005\022\014\n\004bean\030\006 " +
      "\001(\005\022\017\n\007diamond\030\007 \001(\005\"\013\n\tGetPlayer\",\n\013Get" +
      "PlayerTo\022\035\n\006player\030\001 \001(\0132\r.Msg.PlayerMo\"" +
      "/\n\016UpdatePlayerNo\022\035\n\006player\030\001 \001(\0132\r.Msg." +
      "PlayerMoB\016\n\ncom.su.msgH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Msg_PlayerMo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Msg_PlayerMo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_PlayerMo_descriptor,
        new java.lang.String[] { "Id", "Account", "Avatar", "Name", "Gender", "Bean", "Diamond", });
    internal_static_Msg_GetPlayer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Msg_GetPlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_GetPlayer_descriptor,
        new java.lang.String[] { });
    internal_static_Msg_GetPlayerTo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Msg_GetPlayerTo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_GetPlayerTo_descriptor,
        new java.lang.String[] { "Player", });
    internal_static_Msg_UpdatePlayerNo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Msg_UpdatePlayerNo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_UpdatePlayerNo_descriptor,
        new java.lang.String[] { "Player", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
