// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RankingMsg.proto

package com.su.msg;

public final class RankingMsg {
  private RankingMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RankingMoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg.RankingMo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional int32 sex = 3;</code>
     */
    boolean hasSex();
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional int32 sex = 3;</code>
     */
    int getSex();

    /**
     * <pre>
     * 头衔
     * </pre>
     *
     * <code>optional int32 title = 4;</code>
     */
    boolean hasTitle();
    /**
     * <pre>
     * 头衔
     * </pre>
     *
     * <code>optional int32 title = 4;</code>
     */
    int getTitle();

    /**
     * <pre>
     * 得分
     * </pre>
     *
     * <code>optional int32 score = 5;</code>
     */
    boolean hasScore();
    /**
     * <pre>
     * 得分
     * </pre>
     *
     * <code>optional int32 score = 5;</code>
     */
    int getScore();
  }
  /**
   * <pre>
   * 排行信息
   * </pre>
   *
   * Protobuf type {@code Msg.RankingMo}
   */
  public  static final class RankingMo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg.RankingMo)
      RankingMoOrBuilder {
    // Use RankingMo.newBuilder() to construct.
    private RankingMo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RankingMo() {
      id_ = 0L;
      name_ = "";
      sex_ = 0;
      title_ = 0;
      score_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RankingMo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sex_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              title_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              score_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.RankingMsg.internal_static_Msg_RankingMo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.RankingMsg.internal_static_Msg_RankingMo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.RankingMsg.RankingMo.class, com.su.msg.RankingMsg.RankingMo.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional int32 sex = 3;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 性别
     * </pre>
     *
     * <code>optional int32 sex = 3;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int TITLE_FIELD_NUMBER = 4;
    private int title_;
    /**
     * <pre>
     * 头衔
     * </pre>
     *
     * <code>optional int32 title = 4;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 头衔
     * </pre>
     *
     * <code>optional int32 title = 4;</code>
     */
    public int getTitle() {
      return title_;
    }

    public static final int SCORE_FIELD_NUMBER = 5;
    private int score_;
    /**
     * <pre>
     * 得分
     * </pre>
     *
     * <code>optional int32 score = 5;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 得分
     * </pre>
     *
     * <code>optional int32 score = 5;</code>
     */
    public int getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, sex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, title_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, score_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, title_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, score_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.RankingMsg.RankingMo)) {
        return super.equals(obj);
      }
      com.su.msg.RankingMsg.RankingMo other = (com.su.msg.RankingMsg.RankingMo) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasSex() == other.hasSex());
      if (hasSex()) {
        result = result && (getSex()
            == other.getSex());
      }
      result = result && (hasTitle() == other.hasTitle());
      if (hasTitle()) {
        result = result && (getTitle()
            == other.getTitle());
      }
      result = result && (hasScore() == other.hasScore());
      if (hasScore()) {
        result = result && (getScore()
            == other.getScore());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasSex()) {
        hash = (37 * hash) + SEX_FIELD_NUMBER;
        hash = (53 * hash) + getSex();
      }
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle();
      }
      if (hasScore()) {
        hash = (37 * hash) + SCORE_FIELD_NUMBER;
        hash = (53 * hash) + getScore();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.RankingMsg.RankingMo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.RankingMsg.RankingMo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.RankingMo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.RankingMsg.RankingMo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.RankingMo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.RankingMsg.RankingMo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.RankingMo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.RankingMsg.RankingMo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.RankingMo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.RankingMsg.RankingMo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.RankingMsg.RankingMo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 排行信息
     * </pre>
     *
     * Protobuf type {@code Msg.RankingMo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg.RankingMo)
        com.su.msg.RankingMsg.RankingMoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.RankingMsg.internal_static_Msg_RankingMo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.RankingMsg.internal_static_Msg_RankingMo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.RankingMsg.RankingMo.class, com.su.msg.RankingMsg.RankingMo.Builder.class);
      }

      // Construct using com.su.msg.RankingMsg.RankingMo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.RankingMsg.internal_static_Msg_RankingMo_descriptor;
      }

      public com.su.msg.RankingMsg.RankingMo getDefaultInstanceForType() {
        return com.su.msg.RankingMsg.RankingMo.getDefaultInstance();
      }

      public com.su.msg.RankingMsg.RankingMo build() {
        com.su.msg.RankingMsg.RankingMo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.RankingMsg.RankingMo buildPartial() {
        com.su.msg.RankingMsg.RankingMo result = new com.su.msg.RankingMsg.RankingMo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.RankingMsg.RankingMo) {
          return mergeFrom((com.su.msg.RankingMsg.RankingMo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.RankingMsg.RankingMo other) {
        if (other == com.su.msg.RankingMsg.RankingMo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.RankingMsg.RankingMo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.RankingMsg.RankingMo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       * 玩家id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 玩家id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 玩家id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家id
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional int32 sex = 3;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional int32 sex = 3;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional int32 sex = 3;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000004;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 性别
       * </pre>
       *
       * <code>optional int32 sex = 3;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        onChanged();
        return this;
      }

      private int title_ ;
      /**
       * <pre>
       * 头衔
       * </pre>
       *
       * <code>optional int32 title = 4;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 头衔
       * </pre>
       *
       * <code>optional int32 title = 4;</code>
       */
      public int getTitle() {
        return title_;
      }
      /**
       * <pre>
       * 头衔
       * </pre>
       *
       * <code>optional int32 title = 4;</code>
       */
      public Builder setTitle(int value) {
        bitField0_ |= 0x00000008;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头衔
       * </pre>
       *
       * <code>optional int32 title = 4;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        title_ = 0;
        onChanged();
        return this;
      }

      private int score_ ;
      /**
       * <pre>
       * 得分
       * </pre>
       *
       * <code>optional int32 score = 5;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * 得分
       * </pre>
       *
       * <code>optional int32 score = 5;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <pre>
       * 得分
       * </pre>
       *
       * <code>optional int32 score = 5;</code>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000010;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 得分
       * </pre>
       *
       * <code>optional int32 score = 5;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000010);
        score_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg.RankingMo)
    }

    // @@protoc_insertion_point(class_scope:Msg.RankingMo)
    private static final com.su.msg.RankingMsg.RankingMo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.RankingMsg.RankingMo();
    }

    public static com.su.msg.RankingMsg.RankingMo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RankingMo>
        PARSER = new com.google.protobuf.AbstractParser<RankingMo>() {
      public RankingMo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RankingMo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RankingMo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RankingMo> getParserForType() {
      return PARSER;
    }

    public com.su.msg.RankingMsg.RankingMo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetRankingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg.GetRanking)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 排行榜类型
     * </pre>
     *
     * <code>optional int32 type = 1;</code>
     */
    boolean hasType();
    /**
     * <pre>
     * 排行榜类型
     * </pre>
     *
     * <code>optional int32 type = 1;</code>
     */
    int getType();
  }
  /**
   * <pre>
   * 获取排行榜信息
   * </pre>
   *
   * Protobuf type {@code Msg.GetRanking}
   */
  public  static final class GetRanking extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg.GetRanking)
      GetRankingOrBuilder {
    // Use GetRanking.newBuilder() to construct.
    private GetRanking(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRanking() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetRanking(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.RankingMsg.internal_static_Msg_GetRanking_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.RankingMsg.internal_static_Msg_GetRanking_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.RankingMsg.GetRanking.class, com.su.msg.RankingMsg.GetRanking.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 排行榜类型
     * </pre>
     *
     * <code>optional int32 type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 排行榜类型
     * </pre>
     *
     * <code>optional int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.RankingMsg.GetRanking)) {
        return super.equals(obj);
      }
      com.su.msg.RankingMsg.GetRanking other = (com.su.msg.RankingMsg.GetRanking) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && (getType()
            == other.getType());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.RankingMsg.GetRanking parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.RankingMsg.GetRanking parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.GetRanking parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.RankingMsg.GetRanking parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.GetRanking parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.RankingMsg.GetRanking parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.GetRanking parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.RankingMsg.GetRanking parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.GetRanking parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.RankingMsg.GetRanking parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.RankingMsg.GetRanking prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 获取排行榜信息
     * </pre>
     *
     * Protobuf type {@code Msg.GetRanking}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg.GetRanking)
        com.su.msg.RankingMsg.GetRankingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.RankingMsg.internal_static_Msg_GetRanking_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.RankingMsg.internal_static_Msg_GetRanking_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.RankingMsg.GetRanking.class, com.su.msg.RankingMsg.GetRanking.Builder.class);
      }

      // Construct using com.su.msg.RankingMsg.GetRanking.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.RankingMsg.internal_static_Msg_GetRanking_descriptor;
      }

      public com.su.msg.RankingMsg.GetRanking getDefaultInstanceForType() {
        return com.su.msg.RankingMsg.GetRanking.getDefaultInstance();
      }

      public com.su.msg.RankingMsg.GetRanking build() {
        com.su.msg.RankingMsg.GetRanking result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.RankingMsg.GetRanking buildPartial() {
        com.su.msg.RankingMsg.GetRanking result = new com.su.msg.RankingMsg.GetRanking(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.RankingMsg.GetRanking) {
          return mergeFrom((com.su.msg.RankingMsg.GetRanking)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.RankingMsg.GetRanking other) {
        if (other == com.su.msg.RankingMsg.GetRanking.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.RankingMsg.GetRanking parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.RankingMsg.GetRanking) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <pre>
       * 排行榜类型
       * </pre>
       *
       * <code>optional int32 type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 排行榜类型
       * </pre>
       *
       * <code>optional int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 排行榜类型
       * </pre>
       *
       * <code>optional int32 type = 1;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 排行榜类型
       * </pre>
       *
       * <code>optional int32 type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg.GetRanking)
    }

    // @@protoc_insertion_point(class_scope:Msg.GetRanking)
    private static final com.su.msg.RankingMsg.GetRanking DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.RankingMsg.GetRanking();
    }

    public static com.su.msg.RankingMsg.GetRanking getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetRanking>
        PARSER = new com.google.protobuf.AbstractParser<GetRanking>() {
      public GetRanking parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetRanking(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetRanking> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRanking> getParserForType() {
      return PARSER;
    }

    public com.su.msg.RankingMsg.GetRanking getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetRankingToOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg.GetRankingTo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Msg.RankingMo ranking = 1;</code>
     */
    java.util.List<com.su.msg.RankingMsg.RankingMo> 
        getRankingList();
    /**
     * <code>repeated .Msg.RankingMo ranking = 1;</code>
     */
    com.su.msg.RankingMsg.RankingMo getRanking(int index);
    /**
     * <code>repeated .Msg.RankingMo ranking = 1;</code>
     */
    int getRankingCount();
    /**
     * <code>repeated .Msg.RankingMo ranking = 1;</code>
     */
    java.util.List<? extends com.su.msg.RankingMsg.RankingMoOrBuilder> 
        getRankingOrBuilderList();
    /**
     * <code>repeated .Msg.RankingMo ranking = 1;</code>
     */
    com.su.msg.RankingMsg.RankingMoOrBuilder getRankingOrBuilder(
        int index);

    /**
     * <pre>
     * 我的排名
     * </pre>
     *
     * <code>optional int32 myRank = 2;</code>
     */
    boolean hasMyRank();
    /**
     * <pre>
     * 我的排名
     * </pre>
     *
     * <code>optional int32 myRank = 2;</code>
     */
    int getMyRank();
  }
  /**
   * Protobuf type {@code Msg.GetRankingTo}
   */
  public  static final class GetRankingTo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg.GetRankingTo)
      GetRankingToOrBuilder {
    // Use GetRankingTo.newBuilder() to construct.
    private GetRankingTo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRankingTo() {
      ranking_ = java.util.Collections.emptyList();
      myRank_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetRankingTo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ranking_ = new java.util.ArrayList<com.su.msg.RankingMsg.RankingMo>();
                mutable_bitField0_ |= 0x00000001;
              }
              ranking_.add(
                  input.readMessage(com.su.msg.RankingMsg.RankingMo.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              myRank_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ranking_ = java.util.Collections.unmodifiableList(ranking_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.su.msg.RankingMsg.internal_static_Msg_GetRankingTo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.su.msg.RankingMsg.internal_static_Msg_GetRankingTo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.su.msg.RankingMsg.GetRankingTo.class, com.su.msg.RankingMsg.GetRankingTo.Builder.class);
    }

    private int bitField0_;
    public static final int RANKING_FIELD_NUMBER = 1;
    private java.util.List<com.su.msg.RankingMsg.RankingMo> ranking_;
    /**
     * <code>repeated .Msg.RankingMo ranking = 1;</code>
     */
    public java.util.List<com.su.msg.RankingMsg.RankingMo> getRankingList() {
      return ranking_;
    }
    /**
     * <code>repeated .Msg.RankingMo ranking = 1;</code>
     */
    public java.util.List<? extends com.su.msg.RankingMsg.RankingMoOrBuilder> 
        getRankingOrBuilderList() {
      return ranking_;
    }
    /**
     * <code>repeated .Msg.RankingMo ranking = 1;</code>
     */
    public int getRankingCount() {
      return ranking_.size();
    }
    /**
     * <code>repeated .Msg.RankingMo ranking = 1;</code>
     */
    public com.su.msg.RankingMsg.RankingMo getRanking(int index) {
      return ranking_.get(index);
    }
    /**
     * <code>repeated .Msg.RankingMo ranking = 1;</code>
     */
    public com.su.msg.RankingMsg.RankingMoOrBuilder getRankingOrBuilder(
        int index) {
      return ranking_.get(index);
    }

    public static final int MYRANK_FIELD_NUMBER = 2;
    private int myRank_;
    /**
     * <pre>
     * 我的排名
     * </pre>
     *
     * <code>optional int32 myRank = 2;</code>
     */
    public boolean hasMyRank() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 我的排名
     * </pre>
     *
     * <code>optional int32 myRank = 2;</code>
     */
    public int getMyRank() {
      return myRank_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < ranking_.size(); i++) {
        output.writeMessage(1, ranking_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, myRank_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < ranking_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ranking_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, myRank_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.su.msg.RankingMsg.GetRankingTo)) {
        return super.equals(obj);
      }
      com.su.msg.RankingMsg.GetRankingTo other = (com.su.msg.RankingMsg.GetRankingTo) obj;

      boolean result = true;
      result = result && getRankingList()
          .equals(other.getRankingList());
      result = result && (hasMyRank() == other.hasMyRank());
      if (hasMyRank()) {
        result = result && (getMyRank()
            == other.getMyRank());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRankingCount() > 0) {
        hash = (37 * hash) + RANKING_FIELD_NUMBER;
        hash = (53 * hash) + getRankingList().hashCode();
      }
      if (hasMyRank()) {
        hash = (37 * hash) + MYRANK_FIELD_NUMBER;
        hash = (53 * hash) + getMyRank();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.su.msg.RankingMsg.GetRankingTo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.RankingMsg.GetRankingTo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.GetRankingTo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.su.msg.RankingMsg.GetRankingTo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.GetRankingTo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.RankingMsg.GetRankingTo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.GetRankingTo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.su.msg.RankingMsg.GetRankingTo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.su.msg.RankingMsg.GetRankingTo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.su.msg.RankingMsg.GetRankingTo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.su.msg.RankingMsg.GetRankingTo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg.GetRankingTo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg.GetRankingTo)
        com.su.msg.RankingMsg.GetRankingToOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.su.msg.RankingMsg.internal_static_Msg_GetRankingTo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.su.msg.RankingMsg.internal_static_Msg_GetRankingTo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.su.msg.RankingMsg.GetRankingTo.class, com.su.msg.RankingMsg.GetRankingTo.Builder.class);
      }

      // Construct using com.su.msg.RankingMsg.GetRankingTo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRankingFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (rankingBuilder_ == null) {
          ranking_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rankingBuilder_.clear();
        }
        myRank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.su.msg.RankingMsg.internal_static_Msg_GetRankingTo_descriptor;
      }

      public com.su.msg.RankingMsg.GetRankingTo getDefaultInstanceForType() {
        return com.su.msg.RankingMsg.GetRankingTo.getDefaultInstance();
      }

      public com.su.msg.RankingMsg.GetRankingTo build() {
        com.su.msg.RankingMsg.GetRankingTo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.su.msg.RankingMsg.GetRankingTo buildPartial() {
        com.su.msg.RankingMsg.GetRankingTo result = new com.su.msg.RankingMsg.GetRankingTo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (rankingBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            ranking_ = java.util.Collections.unmodifiableList(ranking_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.ranking_ = ranking_;
        } else {
          result.ranking_ = rankingBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.myRank_ = myRank_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.su.msg.RankingMsg.GetRankingTo) {
          return mergeFrom((com.su.msg.RankingMsg.GetRankingTo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.su.msg.RankingMsg.GetRankingTo other) {
        if (other == com.su.msg.RankingMsg.GetRankingTo.getDefaultInstance()) return this;
        if (rankingBuilder_ == null) {
          if (!other.ranking_.isEmpty()) {
            if (ranking_.isEmpty()) {
              ranking_ = other.ranking_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRankingIsMutable();
              ranking_.addAll(other.ranking_);
            }
            onChanged();
          }
        } else {
          if (!other.ranking_.isEmpty()) {
            if (rankingBuilder_.isEmpty()) {
              rankingBuilder_.dispose();
              rankingBuilder_ = null;
              ranking_ = other.ranking_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rankingBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRankingFieldBuilder() : null;
            } else {
              rankingBuilder_.addAllMessages(other.ranking_);
            }
          }
        }
        if (other.hasMyRank()) {
          setMyRank(other.getMyRank());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.su.msg.RankingMsg.GetRankingTo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.su.msg.RankingMsg.GetRankingTo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.su.msg.RankingMsg.RankingMo> ranking_ =
        java.util.Collections.emptyList();
      private void ensureRankingIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ranking_ = new java.util.ArrayList<com.su.msg.RankingMsg.RankingMo>(ranking_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.su.msg.RankingMsg.RankingMo, com.su.msg.RankingMsg.RankingMo.Builder, com.su.msg.RankingMsg.RankingMoOrBuilder> rankingBuilder_;

      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public java.util.List<com.su.msg.RankingMsg.RankingMo> getRankingList() {
        if (rankingBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ranking_);
        } else {
          return rankingBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public int getRankingCount() {
        if (rankingBuilder_ == null) {
          return ranking_.size();
        } else {
          return rankingBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public com.su.msg.RankingMsg.RankingMo getRanking(int index) {
        if (rankingBuilder_ == null) {
          return ranking_.get(index);
        } else {
          return rankingBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public Builder setRanking(
          int index, com.su.msg.RankingMsg.RankingMo value) {
        if (rankingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankingIsMutable();
          ranking_.set(index, value);
          onChanged();
        } else {
          rankingBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public Builder setRanking(
          int index, com.su.msg.RankingMsg.RankingMo.Builder builderForValue) {
        if (rankingBuilder_ == null) {
          ensureRankingIsMutable();
          ranking_.set(index, builderForValue.build());
          onChanged();
        } else {
          rankingBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public Builder addRanking(com.su.msg.RankingMsg.RankingMo value) {
        if (rankingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankingIsMutable();
          ranking_.add(value);
          onChanged();
        } else {
          rankingBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public Builder addRanking(
          int index, com.su.msg.RankingMsg.RankingMo value) {
        if (rankingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankingIsMutable();
          ranking_.add(index, value);
          onChanged();
        } else {
          rankingBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public Builder addRanking(
          com.su.msg.RankingMsg.RankingMo.Builder builderForValue) {
        if (rankingBuilder_ == null) {
          ensureRankingIsMutable();
          ranking_.add(builderForValue.build());
          onChanged();
        } else {
          rankingBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public Builder addRanking(
          int index, com.su.msg.RankingMsg.RankingMo.Builder builderForValue) {
        if (rankingBuilder_ == null) {
          ensureRankingIsMutable();
          ranking_.add(index, builderForValue.build());
          onChanged();
        } else {
          rankingBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public Builder addAllRanking(
          java.lang.Iterable<? extends com.su.msg.RankingMsg.RankingMo> values) {
        if (rankingBuilder_ == null) {
          ensureRankingIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ranking_);
          onChanged();
        } else {
          rankingBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public Builder clearRanking() {
        if (rankingBuilder_ == null) {
          ranking_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rankingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public Builder removeRanking(int index) {
        if (rankingBuilder_ == null) {
          ensureRankingIsMutable();
          ranking_.remove(index);
          onChanged();
        } else {
          rankingBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public com.su.msg.RankingMsg.RankingMo.Builder getRankingBuilder(
          int index) {
        return getRankingFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public com.su.msg.RankingMsg.RankingMoOrBuilder getRankingOrBuilder(
          int index) {
        if (rankingBuilder_ == null) {
          return ranking_.get(index);  } else {
          return rankingBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public java.util.List<? extends com.su.msg.RankingMsg.RankingMoOrBuilder> 
           getRankingOrBuilderList() {
        if (rankingBuilder_ != null) {
          return rankingBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ranking_);
        }
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public com.su.msg.RankingMsg.RankingMo.Builder addRankingBuilder() {
        return getRankingFieldBuilder().addBuilder(
            com.su.msg.RankingMsg.RankingMo.getDefaultInstance());
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public com.su.msg.RankingMsg.RankingMo.Builder addRankingBuilder(
          int index) {
        return getRankingFieldBuilder().addBuilder(
            index, com.su.msg.RankingMsg.RankingMo.getDefaultInstance());
      }
      /**
       * <code>repeated .Msg.RankingMo ranking = 1;</code>
       */
      public java.util.List<com.su.msg.RankingMsg.RankingMo.Builder> 
           getRankingBuilderList() {
        return getRankingFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.su.msg.RankingMsg.RankingMo, com.su.msg.RankingMsg.RankingMo.Builder, com.su.msg.RankingMsg.RankingMoOrBuilder> 
          getRankingFieldBuilder() {
        if (rankingBuilder_ == null) {
          rankingBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.su.msg.RankingMsg.RankingMo, com.su.msg.RankingMsg.RankingMo.Builder, com.su.msg.RankingMsg.RankingMoOrBuilder>(
                  ranking_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          ranking_ = null;
        }
        return rankingBuilder_;
      }

      private int myRank_ ;
      /**
       * <pre>
       * 我的排名
       * </pre>
       *
       * <code>optional int32 myRank = 2;</code>
       */
      public boolean hasMyRank() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 我的排名
       * </pre>
       *
       * <code>optional int32 myRank = 2;</code>
       */
      public int getMyRank() {
        return myRank_;
      }
      /**
       * <pre>
       * 我的排名
       * </pre>
       *
       * <code>optional int32 myRank = 2;</code>
       */
      public Builder setMyRank(int value) {
        bitField0_ |= 0x00000002;
        myRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 我的排名
       * </pre>
       *
       * <code>optional int32 myRank = 2;</code>
       */
      public Builder clearMyRank() {
        bitField0_ = (bitField0_ & ~0x00000002);
        myRank_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg.GetRankingTo)
    }

    // @@protoc_insertion_point(class_scope:Msg.GetRankingTo)
    private static final com.su.msg.RankingMsg.GetRankingTo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.su.msg.RankingMsg.GetRankingTo();
    }

    public static com.su.msg.RankingMsg.GetRankingTo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetRankingTo>
        PARSER = new com.google.protobuf.AbstractParser<GetRankingTo>() {
      public GetRankingTo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetRankingTo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetRankingTo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRankingTo> getParserForType() {
      return PARSER;
    }

    public com.su.msg.RankingMsg.GetRankingTo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_RankingMo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_RankingMo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_GetRanking_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_GetRanking_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_GetRankingTo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_GetRankingTo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RankingMsg.proto\022\003Msg\"P\n\tRankingMo\022\n\n\002" +
      "id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\013\n\003sex\030\003 \001(\005\022\r\n\005t" +
      "itle\030\004 \001(\005\022\r\n\005score\030\005 \001(\005\"\032\n\nGetRanking\022" +
      "\014\n\004type\030\001 \001(\005\"?\n\014GetRankingTo\022\037\n\007ranking" +
      "\030\001 \003(\0132\016.Msg.RankingMo\022\016\n\006myRank\030\002 \001(\005B\016" +
      "\n\ncom.su.msgH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Msg_RankingMo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Msg_RankingMo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_RankingMo_descriptor,
        new java.lang.String[] { "Id", "Name", "Sex", "Title", "Score", });
    internal_static_Msg_GetRanking_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Msg_GetRanking_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_GetRanking_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_Msg_GetRankingTo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Msg_GetRankingTo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_GetRankingTo_descriptor,
        new java.lang.String[] { "Ranking", "MyRank", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
